"""R2 formula reference registry (honest: no fake book pages)."""
from __future__ import annotations

REFERENCES: list[dict] = [
    {
        "mechanic": "year_fraction_act_360",
        "formula": "days(start,end)/360",
        "source": "industry money-market convention; Hull/Tuckman cited as catalog IDs only",
        "source_ids": ["hull_options_futures_derivatives", "tuckman_serrat_fixed_income"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "ACT/360",
        "units": "YEARS",
        "implementation_file": "scripts/lib/research_governance/mechanics/common.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_day_count_act_360",
        "known_limitations": "Not ACT/365.25.",
    },
    {
        "mechanic": "year_fraction_30_360_us",
        "formula": "NASD/SIA 30/360 days / 360",
        "source": "US municipal/corporate SIA 30/360; 30/360 without suffix is rejected as ambiguous",
        "source_ids": ["tuckman_serrat_fixed_income", "thau_bond_book"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "30/360_US",
        "units": "YEARS",
        "implementation_file": "scripts/lib/research_governance/mechanics/common.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_day_count_30_360_us",
        "known_limitations": "ICMA 30E/360 unsupported.",
    },
    {
        "mechanic": "dirty_price",
        "formula": "sum CF_t / (1+y/m)^(m*t); dirty = clean + accrued",
        "source": "standard discounted cash-flow bond identity",
        "source_ids": ["tuckman_serrat_fixed_income", "thau_bond_book"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "annual nominal yield compounded at coupon frequency; PER_100_FACE",
        "units": "PER_100_FACE",
        "implementation_file": "scripts/lib/research_governance/mechanics/fixed_income.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_clean_plus_accrued_equals_dirty",
        "known_limitations": "No OAS, no credit curve.",
    },
    {
        "mechanic": "ytm",
        "formula": "solve dirty(y) = target; Newton with bracket fallback",
        "source": "standard IRR/YTM inversion",
        "source_ids": ["tuckman_serrat_fixed_income"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "nominal annual, coupon frequency compounding",
        "units": "DECIMAL_RATE",
        "implementation_file": "scripts/lib/research_governance/mechanics/fixed_income.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_zero_coupon_ytm_golden",
        "known_limitations": "Fails closed if unbracketed or residual large.",
    },
    {
        "mechanic": "ytw",
        "formula": "min(valid YTM, YTC paths); UNAVAILABLE if call schedule incomplete",
        "source": "standard yield-to-worst definition; no inferred calls",
        "source_ids": ["thau_bond_book", "tuckman_serrat_fixed_income"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "contractual paths only",
        "units": "DECIMAL_RATE",
        "implementation_file": "scripts/lib/research_governance/mechanics/fixed_income.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_ytw_selects_minimum_path",
        "known_limitations": "Does not model make-whole or sinking funds.",
    },
    {
        "mechanic": "macaulay_modified_duration",
        "formula": "Mac = Σ t·PV(CF)/P ; Mod = Mac / (1+y/m)",
        "source": "standard Macaulay/modified identity",
        "source_ids": ["tuckman_serrat_fixed_income"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "years; nominal yield at coupon frequency",
        "units": "YEARS",
        "implementation_file": "scripts/lib/research_governance/mechanics/fixed_income.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_macaulay_duration_golden",
        "known_limitations": "Not effective duration (no option-adjusted).",
    },
    {
        "mechanic": "dv01",
        "formula": "modified_duration * dirty * 1e-4  (per 100 face)",
        "source": "PVBP ≈ modified duration × price × 1bp",
        "source_ids": ["tuckman_serrat_fixed_income"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "+1bp yield; per-100 vs position dollars are distinct fields",
        "units": "PER_100_FACE",
        "implementation_file": "scripts/lib/research_governance/mechanics/fixed_income.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_dv01_finite_difference",
        "known_limitations": "Linear local approximation.",
    },
    {
        "mechanic": "convexity",
        "formula": "Σ t(t+1/m) PV(CF) / (P (1+y/m)^2)",
        "source": "standard periodic-compounding convexity",
        "source_ids": ["tuckman_serrat_fixed_income"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "years^2 per unit yield",
        "units": "YEARS",
        "implementation_file": "scripts/lib/research_governance/mechanics/fixed_income.py",
        "golden_test": "tests/test_research_mechanics_fixed_income.py::test_convexity_finite_difference",
        "known_limitations": "Compared to finite-difference second derivative.",
    },
    {
        "mechanic": "etf_premium_discount",
        "formula": "market_price/nav - 1",
        "source": "standard premium/discount; official vs indicative vs proxy enumerated",
        "source_ids": ["ferri_etf_book"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "compatible currency/share class; timestamp tolerance",
        "units": "PERCENT / DECIMAL_RATE",
        "implementation_file": "scripts/lib/research_governance/mechanics/etf.py",
        "golden_test": "tests/test_research_mechanics_etf.py::test_premium_discount_golden",
        "known_limitations": "No SEC Form N-PORT primary registered in catalog.",
    },
    {
        "mechanic": "tracking_error",
        "formula": "stdev(TD) * sqrt(annualization_factor)",
        "source": "standard TE definition; frequency must be declared",
        "source_ids": ["ferri_etf_book"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "sample vs population explicit",
        "units": "same as tracking-difference series",
        "implementation_file": "scripts/lib/research_governance/mechanics/etf.py",
        "golden_test": "tests/test_research_mechanics_etf.py::test_tracking_error_golden",
        "known_limitations": "N=1 is UNAVAILABLE.",
    },
    {
        "mechanic": "spread_bps",
        "formula": "(ask-bid)/mid * 10000",
        "source": "quoted spread in basis points",
        "source_ids": ["harris_trading_exchanges"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "reject ask<bid and non-positive quotes",
        "units": "BASIS_POINTS",
        "implementation_file": "scripts/lib/research_governance/mechanics/etf.py",
        "golden_test": "tests/test_research_mechanics_etf.py::test_spread_bps_golden",
        "known_limitations": "Quoted, not effective, spread.",
    },
    {
        "mechanic": "gordon_terminal_value",
        "formula": "TV = FCF_n*(1+g)/(WACC-g)  requiring WACC>g",
        "source": "Gordon growth; Damodaran catalog id only",
        "source_ids": ["damodaran_on_valuation"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "end-of-year discounting",
        "units": "USD",
        "implementation_file": "scripts/lib/research_governance/mechanics/valuation.py",
        "golden_test": "tests/test_research_mechanics_valuation.py::test_terminal_value_golden",
        "known_limitations": "CONDITIONAL MODEL OUTPUT, not financial truth.",
    },
    {
        "mechanic": "reverse_dcf_growth",
        "formula": "solve equity(g_fcf) = target; unique in-domain root only",
        "source": "market-implied expectations idea; Expectations Investing catalog id only",
        "source_ids": ["expectations_investing_rappaport_mauboussin", "damodaran_on_valuation"],
        "source_status": "SOURCE_CLAIM_INCOMPLETE",
        "convention": "one unknown at a time; multiple roots → UNAVAILABLE",
        "units": "DECIMAL_RATE",
        "implementation_file": "scripts/lib/research_governance/mechanics/valuation.py",
        "golden_test": "tests/test_research_mechanics_valuation.py::test_reverse_growth_golden",
        "known_limitations": "Does not say what growth will occur.",
    },
]


def all_references() -> list[dict]:
    return list(REFERENCES)
