"""WAVE G3 — docs index generator wired from report_docs_inventory.py.

Invariants:
  * docs/INDEX.md is generated by scripts/report_docs_inventory.py (no third mechanism)
  * --check-index regenerates and fails on drift
  * MISSING HEADER is counted for markdown lacking a structured header
  * config/lane_registry.json has docs-index with an output_signal
  * this test file is on the hardening CI allowlist
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "report_docs_inventory.py"
INDEX = ROOT / "docs" / "INDEX.md"
REGISTRY = ROOT / "config" / "lane_registry.json"
HARDENING = ROOT / "scripts" / "run_cio_hardening_ci.py"


def _load_inventory_mod():
    spec = importlib.util.spec_from_file_location("report_docs_inventory", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def test_g3_index_exists_and_declares_generator():
    assert INDEX.is_file(), "docs/INDEX.md must be committed after --write-index"
    text = INDEX.read_text(encoding="utf-8")
    assert "report_docs_inventory.py" in text
    assert "MISSING HEADER" in text
    assert "Tree fingerprint:" in text
    assert text.startswith("<!-- GENERATED by scripts/report_docs_inventory.py")


def test_g3_check_index_passes_on_committed_tree():
    r = subprocess.run(
        [sys.executable, str(SCRIPT), "--check-index"],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert r.returncode == 0, r.stdout + r.stderr


def test_g3_check_index_fails_on_drift(tmp_path):
    """A gate that can only pass is not a gate — mutate INDEX, confirm red, restore."""
    original = INDEX.read_text(encoding="utf-8")
    try:
        INDEX.write_text(original + "\n<!-- drift probe -->\n", encoding="utf-8")
        r = subprocess.run(
            [sys.executable, str(SCRIPT), "--check-index"],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=300,
        )
        assert r.returncode == 1, r.stdout + r.stderr
        assert "drift" in (r.stderr + r.stdout).lower()
    finally:
        INDEX.write_text(original, encoding="utf-8")
    r2 = subprocess.run(
        [sys.executable, str(SCRIPT), "--check-index"],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert r2.returncode == 0, r2.stdout + r2.stderr


def test_g3_missing_header_count_is_computed():
    mod = _load_inventory_mod()
    _inventory, summary = mod.collect_inventory(ROOT / "docs")
    assert summary["missing_header"] >= 0
    assert summary["header_label"] == "MISSING HEADER"
    assert summary["markdown_total"] >= summary["missing_header"]
    # INDEX surface must match the live count
    text = INDEX.read_text(encoding="utf-8")
    assert f"**MISSING HEADER** | **{summary['missing_header']}**" in text


def test_g3_header_detector_positive_and_negative(tmp_path):
    mod = _load_inventory_mod()
    with_header = "# Title\n\n**Status:** Active\n\nBody\n"
    without = "# Title\n\nJust a paragraph.\n"
    assert mod.has_structured_header(with_header) is True
    assert mod.has_structured_header(without) is False
    yaml_fm = "---\nstatus: active\n---\n# Title\n"
    assert mod.has_structured_header(yaml_fm) is True


def test_g3_lane_registry_row_has_output_signal():
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    rows = [r for r in reg["lanes"] if r.get("lane_id") == "docs-index"]
    assert len(rows) == 1, "exactly one docs-index lane"
    row = rows[0]
    sig = row.get("output_signal") or {}
    assert sig.get("kind") == "file_mtime"
    assert sig.get("path") == "docs/INDEX.md"
    assert row.get("state") == "NEVER_SCHEDULED"
    assert (row.get("scheduler") or {}).get("kind") == "none"


def test_g3_on_hardening_ci_allowlist():
    src = HARDENING.read_text(encoding="utf-8")
    assert "tests/test_overnight_g3_docs_index.py" in src
    assert "overnight_g3_docs_index" in src
    assert "docs_index_drift" in src or "--check-index" in src
