"""Promote fast-forwards the dev tree, or says loudly that it did not.

2026-09-14: a deploy wrapper ran `git merge --ff-only && git log`. Git refused (the promoted commit untracked
files behind the data/runtime and data/audit symlinks whose live content had changed), `set -e` does not
stop on a failed `&&` list, and the deploy reported success with the dev tree — where cron and the user
units run — still on the old commit.

These tests build throwaway repositories; they never touch a real checkout.
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
LIB = ROOT / "scripts" / "lib" / "ff_dev_tree.sh"
DEPLOY = ROOT / "scripts" / "cio_phase2_exact_main_deploy.sh"

COVERS = ["scripts/lib/ff_dev_tree.sh", "scripts/cio_phase2_exact_main_deploy.sh"]

pytestmark = pytest.mark.skipif(not (shutil.which("git") and shutil.which("bash")), reason="needs git and bash")


def _git(cwd: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", *args], cwd=cwd, capture_output=True, text=True, check=True
    )
    return out.stdout.strip()


def _ff(repo: Path, target: str, *, errexit: bool = False) -> subprocess.CompletedProcess:
    prelude = "set -euo pipefail; " if errexit else ""
    script = f'{prelude}source "{LIB}"; ff_dev_tree "$1" "$2" || exit 1'
    return subprocess.run(["bash", "-c", script, "_", str(repo), target], capture_output=True, text=True)


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _origin_and_clone(tmp: Path) -> tuple[Path, Path]:
    origin = tmp / "origin"
    origin.mkdir()
    _git(origin, "init", "-q", "-b", "main")
    return origin, tmp / "dev"


def _symlinked_dev_tree(tmp: Path) -> tuple[Path, Path, Path]:
    """The real shape: data/* ignored, runtime files force-tracked, then served from a symlinked live dir."""
    origin, dev = _origin_and_clone(tmp)
    (origin / "data" / "runtime").mkdir(parents=True)
    (origin / "data" / "runtime" / "manifest.json").write_text("v1\n")
    (origin / "data" / "runtime" / "caps.json").write_text("caps\n")
    (origin / "app.py").write_text("src\n")
    (origin / ".gitignore").write_text("data/*\n")
    _git(origin, "add", ".gitignore", "app.py")
    _git(origin, "add", "-f", "data/runtime/manifest.json", "data/runtime/caps.json")
    _git(origin, "commit", "-qm", "base")
    _git(tmp, "clone", "-q", str(origin), str(dev))
    live = tmp / "persistent-state"
    live.mkdir()
    for name in ("manifest.json", "caps.json"):
        shutil.move(dev / "data" / "runtime" / name, live / name)
    (dev / "data" / "runtime").rmdir()
    (dev / "data" / "runtime").symlink_to(live)
    (live / "manifest.json").write_text("v2 regenerated by a deploy\n")  # live content moved on
    _git(origin, "rm", "-q", "--cached", "data/runtime/manifest.json", "data/runtime/caps.json")
    _git(origin, "commit", "-qm", "untrack runtime files served from persistent state")
    _git(dev, "fetch", "-q", "origin")
    return origin, dev, live


def test_plain_ff_only_refuses_the_symlinked_case(tmp_path):
    _, dev, _ = _symlinked_dev_tree(tmp_path)
    r = subprocess.run(["git", "merge", "--ff-only", "-q", "origin/main"], cwd=dev, capture_output=True, text=True)
    assert r.returncode != 0 and "would be overwritten" in r.stderr


@pytest.mark.parametrize("errexit", [False, True])
def test_symlinked_untracked_files_fast_forward_and_live_copies_are_untouched(tmp_path, errexit):
    _, dev, live = _symlinked_dev_tree(tmp_path)
    before = {p.name: _sha(p) for p in live.iterdir()}
    r = _ff(dev, "origin/main", errexit=errexit)
    assert r.returncode == 0, r.stdout + r.stderr
    assert _git(dev, "rev-parse", "HEAD") == _git(dev, "rev-parse", "origin/main")
    assert {p.name: _sha(p) for p in live.iterdir()} == before
    assert (live / "manifest.json").read_text() == "v2 regenerated by a deploy\n"
    assert _git(dev, "status", "--short") == ""
    assert "live copies unchanged" in r.stdout


def test_a_local_edit_to_a_still_tracked_file_stops_and_changes_nothing(tmp_path):
    origin, dev = _origin_and_clone(tmp_path)
    (origin / "app.py").write_text("base\n")
    _git(origin, "add", "-A")
    _git(origin, "commit", "-qm", "base")
    _git(tmp_path, "clone", "-q", str(origin), str(dev))
    (origin / "app.py").write_text("upstream\n")
    _git(origin, "commit", "-qam", "upstream")
    (dev / "app.py").write_text("local edit\n")
    _git(dev, "fetch", "-q", "origin")
    head, index = _git(dev, "rev-parse", "HEAD"), _git(dev, "ls-files", "-s")
    r = _ff(dev, "origin/main")
    assert r.returncode != 0
    assert "STOP" in r.stdout and "app.py" in r.stdout
    assert _git(dev, "rev-parse", "HEAD") == head and _git(dev, "ls-files", "-s") == index
    assert (dev / "app.py").read_text() == "local edit\n"


def test_a_plain_fast_forward_succeeds(tmp_path):
    origin, dev = _origin_and_clone(tmp_path)
    (origin / "app.py").write_text("base\n")
    _git(origin, "add", "-A")
    _git(origin, "commit", "-qm", "base")
    _git(tmp_path, "clone", "-q", str(origin), str(dev))
    (origin / "app.py").write_text("more\n")
    _git(origin, "commit", "-qam", "more")
    _git(dev, "fetch", "-q", "origin")
    r = _ff(dev, "origin/main")
    assert r.returncode == 0, r.stdout
    assert _git(dev, "rev-parse", "HEAD") == _git(dev, "rev-parse", "origin/main")


def test_a_dev_tree_already_past_the_target_is_left_alone(tmp_path):
    origin, dev = _origin_and_clone(tmp_path)
    (origin / "app.py").write_text("base\n")
    _git(origin, "add", "-A")
    _git(origin, "commit", "-qm", "base")
    old = _git(origin, "rev-parse", "HEAD")
    (origin / "app.py").write_text("newer\n")
    _git(origin, "commit", "-qam", "newer")
    _git(tmp_path, "clone", "-q", str(origin), str(dev))
    head = _git(dev, "rev-parse", "HEAD")
    r = _ff(dev, old)
    assert r.returncode == 0 and "already contains" in r.stdout
    assert _git(dev, "rev-parse", "HEAD") == head


def test_promote_fast_forwards_the_dev_tree_after_promote_ok_and_fails_loudly():
    text = DEPLOY.read_text()
    promote = text[text.index("cmd_promote() {") :]
    promote = promote[: promote.index("\n}\n")]
    assert promote.index('log "PROMOTE OK live=$sha"') < promote.index('ff_dev_tree_after_promote "$sha"')
    helper = text[text.index("ff_dev_tree_after_promote() {") :]
    helper = helper[: helper.index("\n}\n")]
    assert 'source "${ROOT}/scripts/lib/ff_dev_tree.sh"' in helper
    assert 'ff_dev_tree "${CANONICAL_SOURCE}" "$sha"' in helper
    assert "CIO_DEPLOY_FF_DEV_TREE" in helper and "die " in helper
    # The swallowed-failure shape must not come back.
    assert "merge --ff-only -q origin/main &&" not in text
