-- 20260808_health_agent_schema.sql
-- Backfill DDL for tables that exist in the live database but have no checked-in
-- CREATE statement anywhere in the repository.
--
-- claude_interventions: written by claude_escalation_handler.py (tier-3 LLM
--   resolutions), read by health_agent_llm_review.py and the /api/v2/health
--   dashboard (enriches findings with remediation status).
--
-- system_health_events: written by system_health_agent.py and stop_health_check.py
--   (inline DDL exists in stop_health_check.py:143 but is stale — the live table
--   has 5 extra lifecycle columns added via out-of-band ALTERs).  This migration
--   captures the ACTUAL live schema so a fresh deployment can recreate it.
--
-- Both tables are idempotent (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).

-- ── claude_interventions ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS claude_interventions (
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    escalation_id   text,
    component       text NOT NULL,
    problem         text NOT NULL,
    diagnosis       text,
    solution        text,
    files_changed   text[],
    status          text NOT NULL DEFAULT 'investigating',
    created_at      timestamptz NOT NULL DEFAULT now(),
    resolved_at     timestamptz,
    session_log     text
);

CREATE INDEX IF NOT EXISTS idx_claude_interventions_created
    ON claude_interventions (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_claude_interventions_status
    ON claude_interventions (status);

-- ── system_health_events (full live schema) ──────────────────────────────────

CREATE TABLE IF NOT EXISTS system_health_events (
    id              serial PRIMARY KEY,
    component       text NOT NULL,
    event_type      text NOT NULL,
    severity        text NOT NULL,
    message         text,
    action_taken    text,
    success         boolean,
    created_at      timestamptz DEFAULT now(),
    lifecycle_state text DEFAULT 'active',
    acknowledged_at timestamptz,
    acknowledged_by text,
    resolved_at     timestamptz,
    resolved_by     text
);

CREATE INDEX IF NOT EXISTS idx_she_component ON system_health_events (component);
CREATE INDEX IF NOT EXISTS idx_she_created ON system_health_events (created_at DESC);
