version: 4
weights:
  technical_momentum: 0.0809
  setup_quality: 0.0297
  analyst: 0.5168
  social_sentiment: 0.1149
  sector_strength: 0.0377
  news_catalyst: 0.1149
  risk_reward: 0.1051
auto_grafted_at: '2026-06-27T21:00:01.482438+00:00'
