#!/usr/bin/env python3
"""Every test file is run by CI, or is named and explained.

    python3 scripts/check_test_coverage.py              # report
    python3 scripts/check_test_coverage.py --json
    python3 scripts/check_test_coverage.py --fail-on-new # CI gate

`run_cio_hardening_ci.py` runs an explicit allowlist. Measured 2026-08-30: the
repository holds 993 test files and the allowlist names 49 of them, so **every
green CI run has reported on 5% of the suite** and said nothing about the other
95%. That is not a small gap — it retroactively weakens every "CI green" claim
made against this repository.

Why this gate rather than switching CI to discovery: the unlisted suite does not
pass. Collecting it yields 13,610 tests and 6 files that cannot even be imported,
one of which (`test_gate_a1_suite.py`) raises SystemExit at module scope and
aborts the entire pytest run. A straight flip to discovery would turn CI red on
work unrelated to whatever change triggered it, and a red gate nobody can green
gets disabled — which is how the 95% became invisible in the first place.

So the gap is made VISIBLE and BOUNDED instead: today's unlisted files are seeded
as an explicit baseline, and the gate fails only when a NEW test file appears
that is neither run by CI nor explained. The baseline can only shrink. This is
the same shape as the dark-contract gate, which is the working precedent in this
repo.

Removing a name from UNLISTED_BASELINE is progress. Adding one requires a reason
in DENY, not a silent append.

AUTHORITY: READ_ONLY_ADVISORY. Static analysis only, repo-only inputs.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCHEMA = "TestCoverageAudit@v1"

NO_CONSUMER_REASON = (
    "this IS a CI gate; the workflow invokes it, nothing imports it. Same shape "
    "as check_dark_contracts.py and check_line_endings.py."
)

REPO = Path(__file__).resolve().parents[1]
TESTS = REPO / "tests"

# Files CI must not collect, each with the reason. These are not "unlisted" --
# they are actively excluded, and the reason is the point.
DENY: dict[str, str] = {
    "tests/test_gate_a1_suite.py":
        "raises SystemExit(1) at module scope, which aborts the whole pytest "
        "run with INTERNALERROR rather than failing one file. Must be rewritten "
        "as a test before it can be collected.",
    "tests/test_cio_acceptance_g0_evaluator.py": "collection error 2026-08-30",
    "tests/test_continuous_runner_restore.py": "collection error 2026-08-30",
    "tests/test_continuous_runner_social_injection.py": "collection error 2026-08-30",
    "tests/test_finviz_rvol_backfill.py": "collection error 2026-08-30",
    "tests/test_technical_intelligence_v5.py": "collection error 2026-08-30",
}


# Seeded 2026-08-30: every test file CI did not run at the moment this gate
# landed. Inherited debt, named rather than hidden. This list may shrink and
# must not grow -- a new unlisted file fails the gate.
UNLISTED_BASELINE: frozenset = frozenset([
    "tests/financial_senses/test_acceptance_validate.py",
    "tests/financial_senses/test_cio_critic_shadow.py",
    "tests/financial_senses/test_claim_evidence_graph.py",
    "tests/financial_senses/test_dry_replay.py",
    "tests/financial_senses/test_factor_exposure.py",
    "tests/financial_senses/test_fred_alfred_provider.py",
    "tests/financial_senses/test_instrument_identity.py",
    "tests/financial_senses/test_live_smoke.py",
    "tests/financial_senses/test_manifest.py",
    "tests/financial_senses/test_provider_contract.py",
    "tests/financial_senses/test_sec_filing_diff.py",
    "tests/financial_senses/test_sec_provider.py",
    "tests/financial_senses/test_security_source_governance.py",
    "tests/financial_senses/test_stress_engine.py",
    "tests/provider_cost/test_call_site_instrumentation.py",
    "tests/provider_cost/test_provider_cost.py",
    "tests/test_active_trader_broker_capabilities.py",
    "tests/test_active_trader_config_read.py",
    "tests/test_active_trader_feature_flags.py",
    "tests/test_active_trader_momentum_exit_policy.py",
    "tests/test_active_trader_motion_api.py",
    "tests/test_active_trader_motion_host_proof.py",
    "tests/test_active_trader_motion_journal.py",
    "tests/test_active_trader_motion_runtime.py",
    "tests/test_active_trader_near_ready.py",
    "tests/test_active_trader_permission_queue.py",
    "tests/test_active_trader_policy_fail_closed.py",
    "tests/test_active_trader_session_control.py",
    "tests/test_active_trader_session_http.py",
    "tests/test_active_trader_sim_execution.py",
    "tests/test_active_trader_stage0.py",
    "tests/test_active_trader_t2_jit_policy.py",
    "tests/test_active_trader_venue_eligibility.py",
    "tests/test_advisory_bridge_routing.py",
    "tests/test_advisory_desk_operator.py",
    "tests/test_advisory_desk_phase1.py",
    "tests/test_advisory_desk_phase2.py",
    "tests/test_advisory_desk_phase3.py",
    "tests/test_advisory_desk_phase4.py",
    "tests/test_advisory_desk_phase5.py",
    "tests/test_advisory_desk_phase6.py",
    "tests/test_advisory_desk_phase7.py",
    "tests/test_advisory_desk_run_now.py",
    "tests/test_advisory_desk_trim_policy.py",
    "tests/test_advisory_influence.py",
    "tests/test_advisory_outcome_record.py",
    "tests/test_advisory_shadow_seed.py",
    "tests/test_aegis_evening_packet.py",
    "tests/test_aegis_transcript_discovery_fallback.py",
    "tests/test_afterhours_ready1_candidate_preparation.py",
    "tests/test_agent_context_envelope.py",
    "tests/test_agent_context_integration.py",
    "tests/test_agent_decision_payload.py",
    "tests/test_agent_durable_memory.py",
    "tests/test_agent_feature_flags.py",
    "tests/test_agent_flash_governance.py",
    "tests/test_agent_followup.py",
    "tests/test_agent_intelligence_adversarial.py",
    "tests/test_agent_intelligence_failure_injection.py",
    "tests/test_agent_intelligence_integration.py",
    "tests/test_agent_job_enqueue_governance.py",
    "tests/test_agent_job_provider_policy.py",
    "tests/test_agent_jobs_containment_fail_closed.py",
    "tests/test_agent_jobs_cron_command.py",
    "tests/test_agent_learning_linkage.py",
    "tests/test_agent_maturity_observability.py",
    "tests/test_agent_mem0_provider.py",
    "tests/test_agent_memory_governance.py",
    "tests/test_agent_memory_shadow_measure.py",
    "tests/test_agent_observability.py",
    "tests/test_agent_perf_bench.py",
    "tests/test_agent_performance_calibration.py",
    "tests/test_agent_replay_harness.py",
    "tests/test_agent_run_trace.py",
    "tests/test_agent_runtime_critics.py",
    "tests/test_agent_runtime_deadlines.py",
    "tests/test_agent_runtime_dispatch_backend.py",
    "tests/test_agent_runtime_export_replay.py",
    "tests/test_agent_runtime_host_proof_wrapper.py",
    "tests/test_agent_runtime_identity_monitoring_read_api.py",
    "tests/test_agent_runtime_instrumentation.py",
    "tests/test_agent_runtime_knowledge.py",
    "tests/test_agent_runtime_lab_classifier.py",
    "tests/test_agent_runtime_lab_evolve.py",
    "tests/test_agent_runtime_lab_evolve_from_ref.py",
    "tests/test_agent_runtime_lab_preflight.py",
    "tests/test_agent_runtime_lane_d_agents.py",
    "tests/test_agent_runtime_lane_d_governance.py",
    "tests/test_agent_runtime_lane_d_scheduler.py",
    "tests/test_agent_runtime_lifecycle_integration.py",
    "tests/test_agent_runtime_lifecycle_real_postgres.py",
    "tests/test_agent_runtime_migration_contract.py",
    "tests/test_agent_runtime_missing_modules.py",
    "tests/test_agent_runtime_monitoring.py",
    "tests/test_agent_runtime_mvl.py",
    "tests/test_agent_runtime_persistence.py",
    "tests/test_agent_runtime_read_deploy_boundary.py",
    "tests/test_agent_runtime_read_mount.py",
    "tests/test_agent_runtime_read_postgres.py",
    "tests/test_agent_runtime_real_postgres.py",
    "tests/test_agent_runtime_sentinel.py",
    "tests/test_agent_runtime_sentinel_pipeline.py",
    "tests/test_agent_runtime_watch_artifact.py",
    "tests/test_agent_shadow_acceptance.py",
    "tests/test_agent_trace_retention.py",
    "tests/test_agent_untrusted_data.py",
    "tests/test_agent_wake_taxonomy.py",
    "tests/test_ai_work_policy_hooks.py",
    "tests/test_aif_financial_senses_adversarial.py",
    "tests/test_aif_financial_senses_contract.py",
    "tests/test_aif_financial_senses_replay.py",
    "tests/test_aif_financial_senses_unit.py",
    "tests/test_alert1_telegram_proposal_alerts.py",
    "tests/test_alert2_telegram_callbacks.py",
    "tests/test_alert3_dedicated_channel_and_page.py",
    "tests/test_alert_condition_state.py",
    "tests/test_alert_delivery_recording_db.py",
    "tests/test_alert_fatigue_1_routing.py",
    "tests/test_alert_normalization_blockers.py",
    "tests/test_alert_occurrence_persistence_db.py",
    "tests/test_alpaca_credentials_factory_r2.py",
    "tests/test_alpaca_live_read_client.py",
    "tests/test_alpaca_paper_host_lock.py",
    "tests/test_alpaca_paper_options_executor.py",
    "tests/test_analyst_report_builder.py",
    "tests/test_api_v2_watch_defense_integration.py",
    "tests/test_atm_expiry_telegram_dedup.py",
    "tests/test_atm_paper_lane_fixes.py",
    "tests/test_atp1b_workflow_answers.py",
    "tests/test_atp2_scheduled_research_cadence.py",
    "tests/test_atp3_truth_layer_action_workflow.py",
    "tests/test_atp4_quote_age_sweeper_truth_counters.py",
    "tests/test_atp4b_counter_alignment.py",
    "tests/test_atp5_promoter_quote_age_gate.py",
    "tests/test_atp_alert1_missed_proposal_telegram_escalation.py",
    "tests/test_attr1_attribution_benchmark_truth.py",
    "tests/test_audit_ledger.py",
    "tests/test_autonomy_watchdog.py",
    "tests/test_b1c_bucket2_migration_boundary.py",
    "tests/test_backfill_entry_plan_rr.py",
    "tests/test_backup_enforcer.py",
    "tests/test_board_check3_requires_a_critique.py",
    "tests/test_br1_backup_restore_hardening.py",
    "tests/test_br2a_existing_drive_backup.py",
    "tests/test_brief_reports_truthfully.py",
    "tests/test_broker_adapter_zero_vendor_literals.py",
    "tests/test_broker_entry_pilot.py",
    "tests/test_broker_promote_oversight.py",
    "tests/test_broker_promote_sizing.py",
    "tests/test_broker_proposal_autocal.py",
    "tests/test_broker_proposal_curator.py",
    "tests/test_broker_proposal_queue_ops.py",
    "tests/test_broker_queue_hygiene.py",
    "tests/test_broker_scaffold.py",
    "tests/test_broker_strategy_resolver.py",
    "tests/test_broker_thesis_validity.py",
    "tests/test_broker_trade_plan_gate.py",
    "tests/test_bus_traceability.py",
    "tests/test_canary_exclusion.py",
    "tests/test_canary_gate.py",
    "tests/test_capability_gate_r4.py",
    "tests/test_cash_holdings_boundary.py",
    "tests/test_cash_unreconciled_law.py",
    "tests/test_catalyst_exception.py",
    "tests/test_catalyst_graph.py",
    "tests/test_catalyst_integrations.py",
    "tests/test_catalyst_severity.py",
    "tests/test_cc_v3_boot_no_reload_loop.py",
    "tests/test_cc_v3_cio_office_audit.py",
    "tests/test_cc_v3_gap_closure.py",
    "tests/test_cc_v3_hub_contract.py",
    "tests/test_cc_v3_load_repair.py",
    "tests/test_chart_patterns_v5.py",
    "tests/test_check_cron_sanity_hardened.py",
    "tests/test_checkin_dedupe.py",
    "tests/test_cio_action_ledger.py",
    "tests/test_cio_advisory_curator.py",
    "tests/test_cio_agent_contract_fleet.py",
    "tests/test_cio_agent_handoff_queue.py",
    "tests/test_cio_canonical_identity.py",
    "tests/test_cio_cc_record_narrative_slice_c.py",
    "tests/test_cio_checkpoint3_canaries.py",
    "tests/test_cio_checkpoint4_committee.py",
    "tests/test_cio_checkpoint4_resume.py",
    "tests/test_cio_checkpoint4_synthesis.py",
    "tests/test_cio_closure_adversarial.py",
    "tests/test_cio_converse_decision_thread.py",
    "tests/test_cio_current_truth_provenance.py",
    "tests/test_cio_deploy_fail_closed.py",
    "tests/test_cio_desk_synthesis_freshness.py",
    "tests/test_cio_desk_synthesis_golden.py",
    "tests/test_cio_diligence_p1_ws1.py",
    "tests/test_cio_diligence_p1_ws2_lifecycle.py",
    "tests/test_cio_diligence_p1_ws3_operator_s0.py",
    "tests/test_cio_diligence_p3_instrument_record.py",
    "tests/test_cio_diligence_p4_p5_research_specialists.py",
    "tests/test_cio_diligence_p6_council_determinism.py",
    "tests/test_cio_diligence_p7_notification_matrix.py",
    "tests/test_cio_diligence_p8_mbi_partition.py",
    "tests/test_cio_diligence_scoreboard.py",
    "tests/test_cio_dispositions_identity.py",
    "tests/test_cio_domain_coverage.py",
    "tests/test_cio_duplicate_s1_hygiene.py",
    "tests/test_cio_dust_cash_no_fire.py",
    "tests/test_cio_evidence_checkpoint2.py",
    "tests/test_cio_evidence_domain_wiring.py",
    "tests/test_cio_evidence_ref.py",
    "tests/test_cio_evidence_refresh_on_newer.py",
    "tests/test_cio_final_truth_adversarial.py",
    "tests/test_cio_full_cycle.py",
    "tests/test_cio_gap_auth_01.py",
    "tests/test_cio_gap_earnings_b1.py",
    "tests/test_cio_gap_ir_01.py",
    "tests/test_cio_gap_loop_01.py",
    "tests/test_cio_gap_price_01.py",
    "tests/test_cio_gap_spec_01.py",
    "tests/test_cio_goals_and_dispatcher.py",
    "tests/test_cio_goals_and_reactive.py",
    "tests/test_cio_governed_model_bridge.py",
    "tests/test_cio_grok_critique_lane.py",
    "tests/test_cio_health_boundary.py",
    "tests/test_cio_held_thesis_coverage.py",
    "tests/test_cio_identity_confidence_census.py",
    "tests/test_cio_instrument_record.py",
    "tests/test_cio_intelligence_telegram_keyboard.py",
    "tests/test_cio_investment_product.py",
    "tests/test_cio_item118_cost_basis_as_of.py",
    "tests/test_cio_lineage.py",
    "tests/test_cio_lineage_health.py",
    "tests/test_cio_loop_b1_b3_d1.py",
    "tests/test_cio_market_session.py",
    "tests/test_cio_notification_attribution.py",
    "tests/test_cio_notification_outbox.py",
    "tests/test_cio_notify_freshness_guard.py",
    "tests/test_cio_notify_s6_only_bar.py",
    "tests/test_cio_operator_activation.py",
    "tests/test_cio_operator_desk_loop.py",
    "tests/test_cio_operator_desk_loop_freeform.py",
    "tests/test_cio_operator_product.py",
    "tests/test_cio_operator_ticker_feedback.py",
    "tests/test_cio_opportunity_queue.py",
    "tests/test_cio_orphan_plan_hygiene.py",
    "tests/test_cio_outcome_learning.py",
    "tests/test_cio_outcome_observer.py",
    "tests/test_cio_p0_identity.py",
    "tests/test_cio_p0_learning.py",
    "tests/test_cio_p0_semantics.py",
    "tests/test_cio_persistent_cognition.py",
    "tests/test_cio_phase_a_s3_notify_gate.py",
    "tests/test_cio_pipeline_slice10_p90_voice.py",
    "tests/test_cio_pipeline_slice11_admissibility.py",
    "tests/test_cio_pipeline_slice12_price_outlier.py",
    "tests/test_cio_pipeline_slice13_qa_alert_dedupe.py",
    "tests/test_cio_pipeline_slice14_rebalancer_cio.py",
    "tests/test_cio_pipeline_slice15_subject_guid.py",
    "tests/test_cio_pipeline_slice16_persist_fairness.py",
    "tests/test_cio_pipeline_slice17_home_2b_2c.py",
    "tests/test_cio_pipeline_slice3_reentry_book_labels.py",
    "tests/test_cio_pipeline_slice4_persist_operator_product.py",
    "tests/test_cio_pipeline_slice5_draft_plan_hygiene.py",
    "tests/test_cio_pipeline_slice6_watch_block_summary.py",
    "tests/test_cio_pipeline_slice7_new_if_thesis.py",
    "tests/test_cio_pipeline_slice8_plan_outcome_checkpoints.py",
    "tests/test_cio_pipeline_slice9_case_summary_lessons.py",
    "tests/test_cio_pipeline_step1_research_attach.py",
    "tests/test_cio_pipeline_step2a_case_summary.py",
    "tests/test_cio_pipeline_step2b_2c_surfaces.py",
    "tests/test_cio_plan_enrichment_p2b.py",
    "tests/test_cio_preconditions_board.py",
    "tests/test_cio_product_notify_outbox.py",
    "tests/test_cio_product_reassessment.py",
    "tests/test_cio_provider_retry_v1.py",
    "tests/test_cio_question_id_contract.py",
    "tests/test_cio_r9_2_canon_foundation.py",
    "tests/test_cio_r9_2_feedback_learning.py",
    "tests/test_cio_r9_2_market_seasonality.py",
    "tests/test_cio_r9_2_policy_portfolio_state.py",
    "tests/test_cio_r9_2_portfolio_thesis.py",
    "tests/test_cio_raw_product_dump_suppress.py",
    "tests/test_cio_reentry_s3_wire.py",
    "tests/test_cio_reflection_journal.py",
    "tests/test_cio_regenerate_stale_plans.py",
    "tests/test_cio_registry_orphan_census.py",
    "tests/test_cio_rehydrate_slice_b.py",
    "tests/test_cio_research_budget_slice_d.py",
    "tests/test_cio_research_gate_v2.py",
    "tests/test_cio_residual_web_lane.py",
    "tests/test_cio_residual_web_live_path.py",
    "tests/test_cio_reverse_factor_backfill.py",
    "tests/test_cio_rollback.py",
    "tests/test_cio_s0_operator_loop.py",
    "tests/test_cio_s6_dust_rule.py",
    "tests/test_cio_signed_digest_mismatch.py",
    "tests/test_cio_situations_phase2a.py",
    "tests/test_cio_stage2b_agent_evidence.py",
    "tests/test_cio_symbol_intelligence_card.py",
    "tests/test_cio_telegram_converse.py",
    "tests/test_cio_telegram_delivery_mode.py",
    "tests/test_cio_telegram_plain_ids.py",
    "tests/test_cio_theses_p3.py",
    "tests/test_cio_ui_honesty.py",
    "tests/test_cio_wake_detector.py",
    "tests/test_cio_wake_traces_p5.py",
    "tests/test_cio_watch_s7_wire.py",
    "tests/test_cio_wave2_census.py",
    "tests/test_cio_wave2_scoreboard.py",
    "tests/test_cio_wave2_slice01_held_thesis.py",
    "tests/test_cio_wave2_slice02_prim_thesis.py",
    "tests/test_cio_wave2_slice03_observational_s1.py",
    "tests/test_cio_wave2_slice04_surface_a_status.py",
    "tests/test_cio_wave2_slice05_watch_ready_named.py",
    "tests/test_cio_wave2_slice06_earnings_days.py",
    "tests/test_cio_wave2_slice07_earnings_commentary.py",
    "tests/test_cio_wave2_slice08_coverage.py",
    "tests/test_cio_wave2_slice09_coverage_card.py",
    "tests/test_cio_wave2_slice10_reentry_overlay.py",
    "tests/test_cio_wave2_slice11_thesis_held.py",
    "tests/test_cio_wave2_slice12_dust_coverage.py",
    "tests/test_cio_wave2_slice12a_live_activation.py",
    "tests/test_cio_wave2_slice13_14_identity.py",
    "tests/test_cio_wave2_slice15_18_graph_identity.py",
    "tests/test_cio_wave2_slice19_21_research_fails.py",
    "tests/test_cio_wave2_slice22_31_research_memory.py",
    "tests/test_cio_wave2_slice32_41_honesty.py",
    "tests/test_cio_wave2c_131_160_books.py",
    "tests/test_cio_wave2c_161_190_research.py",
    "tests/test_cio_wave2c_301_308_locks.py",
    "tests/test_cio_wave3a2_library_seed.py",
    "tests/test_cio_wave3a3_french_surface.py",
    "tests/test_cio_wave3a_library_home.py",
    "tests/test_cio_wave3a_registry_wiring.py",
    "tests/test_cio_wave3b_council_policy.py",
    "tests/test_cio_wave3c_silent_loop.py",
    "tests/test_cio_wave3d_history_wiring.py",
    "tests/test_cio_wave3e_cc_block.py",
    "tests/test_cio_whatsapp_p4.py",
    "tests/test_cio_youtube_research_queue.py",
    "tests/test_closed_account_residual.py",
    "tests/test_closed_loop_evaluation.py",
    "tests/test_cloud_consensus_verdict.py",
    "tests/test_consumption_run_manual.py",
    "tests/test_content_intelligence_asset_classes.py",
    "tests/test_control_plane_api.py",
    "tests/test_control_plane_api_v1_baseline.py",
    "tests/test_control_plane_contract_v1.py",
    "tests/test_convergence_packet.py",
    "tests/test_cost_basis_transfer.py",
    "tests/test_cron_remediation_installer.py",
    "tests/test_cursor_guard_ledger.py",
    "tests/test_dark_contract_gate_compiles_first.py",
    "tests/test_dark_contract_guard.py",
    "tests/test_data_conflict_freshness.py",
    "tests/test_decision_action_policy.py",
    "tests/test_decision_packet.py",
    "tests/test_decision_payload_producers.py",
    "tests/test_deepseek_cost_governance.py",
    "tests/test_deepseek_cost_reservation.py",
    "tests/test_deepseek_json_contracts.py",
    "tests/test_deepseek_offpeak_gate.py",
    "tests/test_deepseek_provider_matrix.py",
    "tests/test_deepseek_run_manual_mocked.py",
    "tests/test_deepseek_scheduler_env.py",
    "tests/test_deepseek_tool_replay.py",
    "tests/test_defense_account_exposure.py",
    "tests/test_defense_data_quality.py",
    "tests/test_defense_quality_integration.py",
    "tests/test_defense_recommendations_v10.py",
    "tests/test_defense_weekly_oversight.py",
    "tests/test_deploy_intelligence.py",
    "tests/test_doc_recon1_post_audit_docs.py",
    "tests/test_docs_drive_parity_canonical.py",
    "tests/test_documented_invocations.py",
    "tests/test_drain_contention.py",
    "tests/test_drive_semantic_compare.py",
    "tests/test_earnings_ack_gate.py",
    "tests/test_econfirm_parser.py",
    "tests/test_entry_planner_arithmetic.py",
    "tests/test_entry_planner_gate.py",
    "tests/test_eod_open_trade_alert.py",
    "tests/test_escalation_verify_autonomy.py",
    "tests/test_every_script_compiles.py",
    "tests/test_evidence_bound_approval.py",
    "tests/test_evidence_second_layer.py",
    "tests/test_execution_language_shared_gate.py",
    "tests/test_execution_readiness.py",
    "tests/test_execution_state.py",
    "tests/test_family_semantic_integration.py",
    "tests/test_fidelity_manual_stop_ticket.py",
    "tests/test_fidelity_stop_sync.py",
    "tests/test_field_scoped_instruction_lint.py",
    "tests/test_finviz_enrichment_default_universe.py",
    "tests/test_finviz_momentum_scalp_filters.py",
    "tests/test_finviz_phase0_reconcile.py",
    "tests/test_finviz_phase1_compiler.py",
    "tests/test_finviz_snapshot.py",
    "tests/test_finviz_throttle_coverage.py",
    "tests/test_freshness_stamps.py",
    "tests/test_friction_statement_oer.py",
    "tests/test_fundamentals_freshness.py",
    "tests/test_gate_a_final_suite.py",
    "tests/test_gate_b1_final_verification.py",
    "tests/test_gate_b2_closure.py",
    "tests/test_gate_b_suite.py",
    "tests/test_gate_d_advisory_contract.py",
    "tests/test_gate_d_backlog_policy.py",
    "tests/test_gate_d_evidence_gate.py",
    "tests/test_gate_d_terminal_closure.py",
    "tests/test_gov1_scheduled_governance.py",
    "tests/test_governed_agent_flash_market.py",
    "tests/test_governed_cloud_generation.py",
    "tests/test_health_agent_data_source_remediation.py",
    "tests/test_health_agent_verdict_wiring.py",
    "tests/test_health_alert_throttle.py",
    "tests/test_health_broker_semantics.py",
    "tests/test_health_proposal_pipeline.py",
    "tests/test_health_remediation_outcome.py",
    "tests/test_health_strategy_registry_integrity.py",
    "tests/test_health_watchlist_news_guard.py",
    "tests/test_hermes_analyst_signals.py",
    "tests/test_hermes_autonomous_closure.py",
    "tests/test_hermes_backend_bridge_mock.py",
    "tests/test_hermes_backend_contract.py",
    "tests/test_hermes_backend_stub.py",
    "tests/test_hermes_discovery_coverage.py",
    "tests/test_hermes_discovery_inbox.py",
    "tests/test_hermes_discovery_integration.py",
    "tests/test_hermes_discovery_llm_review.py",
    "tests/test_hermes_discovery_schedule.py",
    "tests/test_hermes_entity_spike_discovery.py",
    "tests/test_hermes_exec_lint_articles.py",
    "tests/test_hermes_goldens.py",
    "tests/test_hermes_governance_api.py",
    "tests/test_hermes_industry_novelty.py",
    "tests/test_hermes_llm_failover.py",
    "tests/test_hermes_maturity_dashboard.py",
    "tests/test_hermes_maturity_hardening.py",
    "tests/test_hermes_outcome_bus_discovery_health.py",
    "tests/test_hermes_outcome_feedback.py",
    "tests/test_hermes_private_proxy_discovery.py",
    "tests/test_hermes_research_budget_guard.py",
    "tests/test_hermes_research_curator.py",
    "tests/test_hermes_research_fingerprint.py",
    "tests/test_hermes_research_loop.py",
    "tests/test_hermes_research_worker_pool.py",
    "tests/test_hermes_research_workspaces.py",
    "tests/test_hermes_scalp_phase3.py",
    "tests/test_hermes_scope_governor.py",
    "tests/test_hermes_score_alerts_semantics.py",
    "tests/test_hermes_stateful_bridge.py",
    "tests/test_hermes_strategy_discovery.py",
    "tests/test_hermes_tag_lift_discovery.py",
    "tests/test_hermes_think_tank.py",
    "tests/test_hermes_threshold_learning.py",
    "tests/test_hermes_white_space_discovery.py",
    "tests/test_high_rvol_manual_review.py",
    "tests/test_holding_day_change.py",
    "tests/test_holdings_health_parse.py",
    "tests/test_holdings_lifecycle.py",
    "tests/test_holdings_pl_if_fired.py",
    "tests/test_holdings_sanity.py",
    "tests/test_holdings_totals_reconcile.py",
    "tests/test_holdings_universe.py",
    "tests/test_hybrid_evidence.py",
    "tests/test_identity_lookup_failure_visible.py",
    "tests/test_identity_memory_module_wiring.py",
    "tests/test_identity_registry.py",
    "tests/test_iem_closed_conn_retry.py",
    "tests/test_inbox_detail_plain.py",
    "tests/test_industry_momentum_dedupe.py",
    "tests/test_instrument_record.py",
    "tests/test_interlock_registry_r1.py",
    "tests/test_intraday_window_fail_closed.py",
    "tests/test_inverse_stoplights.py",
    "tests/test_job_coverage_rag_matcher.py",
    "tests/test_job_schedule_prioritization.py",
    "tests/test_journal_ai_critique.py",
    "tests/test_journal_auto_tag.py",
    "tests/test_journal_staleness_semantics.py",
    "tests/test_journal_ticker_lifecycle.py",
    "tests/test_journal_ux1_closed_trade_postmortem_dashboard.py",
    "tests/test_journal_ux1b_closed_trade_action_dashboard.py",
    "tests/test_journal_ux2_persistent_lessons_digest.py",
    "tests/test_journal_ux2b_digest_formatting_cron.py",
    "tests/test_kill_switches.py",
    "tests/test_langgraph_complexity_gate.py",
    "tests/test_large_float_social_scout.py",
    "tests/test_lifecycle_bus_slice.py",
    "tests/test_lineage_loop_closure.py",
    "tests/test_lineage_stall_is_visible.py",
    "tests/test_llm_consumption.py",
    "tests/test_llm_content_quality.py",
    "tests/test_llm_governance_no_override.py",
    "tests/test_llm_ledger_excludes_test_processes.py",
    "tests/test_llm_model_registry.py",
    "tests/test_llm_task_policy.py",
    "tests/test_local_model_decommission_audit.py",
    "tests/test_low_price_manual_review.py",
    "tests/test_m2_m3_freeze_safe.py",
    "tests/test_maria_oauth_priority.py",
    "tests/test_maria_one_pass_call_count.py",
    "tests/test_market_observations.py",
    "tests/test_market_quote_provider_schwab.py",
    "tests/test_market_session_calendar.py",
    "tests/test_maturity_control_plane.py",
    "tests/test_maturity_scorecard.py",
    "tests/test_mcp_read_only_gateway.py",
    "tests/test_mcp_security.py",
    "tests/test_mcp_timeout_rate.py",
    "tests/test_memory_admissions_diagnosis.py",
    "tests/test_memory_adversarial_scan_qualifiers.py",
    "tests/test_memory_shadow_measure_honesty.py",
    "tests/test_memory_spine_anchor.py",
    "tests/test_micro_float_manual_review.py",
    "tests/test_miss1_missed_opportunity_audit.py",
    "tests/test_momentum_scalp_config_consistency.py",
    "tests/test_momentum_scalp_expiry_enforced.py",
    "tests/test_momentum_scalp_fast_atm_runner.py",
    "tests/test_momentum_scalp_fast_path_wiring.py",
    "tests/test_momentum_scalp_freshness_sla_report.py",
    "tests/test_momentum_scalp_health_monitor.py",
    "tests/test_momentum_scalp_lead_miner.py",
    "tests/test_momentum_scalp_liquidity_unknown.py",
    "tests/test_momentum_scalp_paper_fast_path.py",
    "tests/test_momentum_scalp_paper_path_diagnosis.py",
    "tests/test_momentum_scalp_paper_path_simulator.py",
    "tests/test_momentum_scalp_regime.py",
    "tests/test_momentum_scalp_source_health.py",
    "tests/test_momentum_scalp_source_latency_sla.py",
    "tests/test_momentum_scalp_source_maturity_report.py",
    "tests/test_momentum_scalp_true_trade_attribution.py",
    "tests/test_momentum_scalp_validation_fast_path.py",
    "tests/test_momentum_scalp_validation_ops_report.py",
    "tests/test_momentum_scalp_validation_quality_gate.py",
    "tests/test_momentum_scalp_validation_tracker.py",
    "tests/test_monthly_advisory_stop_metadata.py",
    "tests/test_moomoo_stage0_preflight.py",
    "tests/test_moomoo_t2.py",
    "tests/test_morning_legacy_fail_closed.py",
    "tests/test_news_ingestion_rotation.py",
    "tests/test_news_symbol_guard.py",
    "tests/test_no_broker_write_bypass.py",
    "tests/test_no_local_generative_routing.py",
    "tests/test_no_ungoverned_cloud_llm_calls.py",
    "tests/test_no_vacuous_assertions.py",
    "tests/test_noc_golden_loop.py",
    "tests/test_nyc_loft_law_domain_pack.py",
    "tests/test_oco_dd_gaps.py",
    "tests/test_ollama_embedding_policy.py",
    "tests/test_opening_intelligence.py",
    "tests/test_operator_product_refresh.py",
    "tests/test_opportunity_book_dedupe.py",
    "tests/test_ops_hygiene1_command_surface_alert_cleanup.py",
    "tests/test_ops_retarget_peak_cron.py",
    "tests/test_ops_tree_pin_audit.py",
    "tests/test_ops_truth1_pipeline_governance_truth.py",
    "tests/test_ops_truth1b_pipeline_warning_alignment.py",
    "tests/test_options_action_gating.py",
    "tests/test_options_card_semantics.py",
    "tests/test_options_earnings_event_model.py",
    "tests/test_options_earnings_vertical_generator.py",
    "tests/test_options_hard_risk_blocks.py",
    "tests/test_options_hard_risk_blocks_matrix.py",
    "tests/test_options_iv_rank.py",
    "tests/test_options_lifecycle_migration.py",
    "tests/test_options_lifecycle_policy.py",
    "tests/test_options_paper_monitor_ops.py",
    "tests/test_options_paper_position_monitor.py",
    "tests/test_options_paper_positions_api.py",
    "tests/test_options_pipeline_atm.py",
    "tests/test_options_pipeline_deep_itm.py",
    "tests/test_options_pipeline_validation.py",
    "tests/test_options_prime_rubric.py",
    "tests/test_options_strategy_matcher.py",
    "tests/test_options_strategy_research.py",
    "tests/test_options_strategy_scanner.py",
    "tests/test_options_universe.py",
    "tests/test_orchestrator_stage_failures.py",
    "tests/test_order_lifecycle.py",
    "tests/test_outbox_process_crash.py",
    "tests/test_outcome_resolution.py",
    "tests/test_outcome_to_lesson.py",
    "tests/test_overnight_llm_policy.py",
    "tests/test_overnight_risk_absence.py",
    "tests/test_p0_tsla_quarantine.py",
    "tests/test_p18_specialist_foundation.py",
    "tests/test_p19_hermes_challenge_queue.py",
    "tests/test_p210_production.py",
    "tests/test_p211_restart.py",
    "tests/test_p26_shadow_autonomy.py",
    "tests/test_p27_operator_communication.py",
    "tests/test_p28_followup_learning.py",
    "tests/test_p29_observability.py",
    "tests/test_p2_cio_run.py",
    "tests/test_packet_d_shadow_dsn_guard.py",
    "tests/test_packet_d_shadow_persistence.py",
    "tests/test_packet_d_shadow_population.py",
    "tests/test_packet_e_promotion_gate.py",
    "tests/test_packet_invalidation.py",
    "tests/test_par1_parallel_hardening_no_backup.py",
    "tests/test_parse_external_research_slices.py",
    "tests/test_phase6_approval_audit_trail.py",
    "tests/test_phase6_market_revalidation.py",
    "tests/test_phase6_market_session_policy.py",
    "tests/test_phase6_proposal_stale_sweeper.py",
    "tests/test_phase6e_scheduled_stale_sweeper.py",
    "tests/test_phase7_approval_simulator.py",
    "tests/test_phase8b_lifecycle_outcomes.py",
    "tests/test_phase8c_lifecycle_dashboard.py",
    "tests/test_phase9a_maturity_hardening.py",
    "tests/test_phase9b_maturity_control_board.py",
    "tests/test_phase9c_scheduled_maturity_board.py",
    "tests/test_pipe_obs1_pipeline_run_telemetry.py",
    "tests/test_pipe_obs1b_visual_enhancements.py",
    "tests/test_pipe_obs2_wrapper_telemetry.py",
    "tests/test_pipe_ops2_actionable_pipeline_operations.py",
    "tests/test_pipeline_liveness.py",
    "tests/test_portfolio_alerts_rebalance.py",
    "tests/test_portfolio_generation_propagation.py",
    "tests/test_portfolio_level_qa_alerts.py",
    "tests/test_portfolio_loader_total_cash_written.py",
    "tests/test_portfolio_report_llm.py",
    "tests/test_portfolio_repricer_total_cash_written.py",
    "tests/test_portfolio_snapshot_sanity.py",
    "tests/test_portfolio_state_write_targets.py",
    "tests/test_position_transfer_normalize.py",
    "tests/test_post_audit_ops1_remaining_backend_fixes.py",
    "tests/test_pp_ux1_paper_proposals_decision_packet.py",
    "tests/test_pp_ux2_proposal_trust_audit.py",
    "tests/test_price_db_sync_backfill.py",
    "tests/test_price_quality.py",
    "tests/test_primary_card_replacement.py",
    "tests/test_promote1_pre_promotion_readiness_gate.py",
    "tests/test_proposal_alert_enrichment.py",
    "tests/test_proposal_decision_gate.py",
    "tests/test_proposal_impact.py",
    "tests/test_protective_policy_oco.py",
    "tests/test_provider_spend_snapshot.py",
    "tests/test_q1_proactive_quote_refresh.py",
    "tests/test_q1b_premarket_quote_refresh.py",
    "tests/test_quote_time_gtc_freshness.py",
    "tests/test_r10_10_memory_shadow.py",
    "tests/test_r10_8_cio_l5.py",
    "tests/test_r10_baseline_curation.py",
    "tests/test_r10_m2_substrate_benchmark.py",
    "tests/test_r10_m3_memory_consolidation.py",
    "tests/test_r10_m4_context_envelope_v2.py",
    "tests/test_r10_memory_architecture_correction.py",
    "tests/test_r10_memory_golden_cases.py",
    "tests/test_r13_api_brain.py",
    "tests/test_r15_1_live.py",
    "tests/test_r15_fabric.py",
    "tests/test_r15_fault_property.py",
    "tests/test_r15_graph_goldens.py",
    "tests/test_r15_gui_lifecycle.py",
    "tests/test_r15_integration.py",
    "tests/test_r15_memory_goldens.py",
    "tests/test_r15_model_goldens.py",
    "tests/test_r15_research_goldens.py",
    "tests/test_r16_integration.py",
    "tests/test_r16_learning.py",
    "tests/test_r17_cash_checkpoint.py",
    "tests/test_r17_faults.py",
    "tests/test_r17_feedback_closure.py",
    "tests/test_r18_2_production_hardening.py",
    "tests/test_r18_data_convergence.py",
    "tests/test_r18_data_operator_convergence.py",
    "tests/test_r18_human_output_goldens.py",
    "tests/test_r20_r24_convergence.py",
    "tests/test_r20_r24_local_gates.py",
    "tests/test_r20_r24_qa_probes.py",
    "tests/test_r20_r24_workflow_acceptance_harness.py",
    "tests/test_r20_v2_hermes_taxonomy.py",
    "tests/test_r20_v2_lineage_checkpoint.py",
    "tests/test_r20_v2_lineage_integration.py",
    "tests/test_r20_v2_registry.py",
    "tests/test_r22_control_plane_fixtures.py",
    "tests/test_r22_pages.py",
    "tests/test_r23_control_plane_pages.py",
    "tests/test_r23_side_by_side_boundary.py",
    "tests/test_r24_audit_page.py",
    "tests/test_r24_control_plane_guards.py",
    "tests/test_r24_learning_page.py",
    "tests/test_r24_maturity_page.py",
    "tests/test_r2_family_liquidity_gating.py",
    "tests/test_r5_yaml_scoring_weights_router.py",
    "tests/test_r93_circulation_p0.py",
    "tests/test_r93_curation_maturity.py",
    "tests/test_r93_free_first_identity.py",
    "tests/test_r93_free_first_scheduler.py",
    "tests/test_rebalance_verifier.py",
    "tests/test_reconcile_orders.py",
    "tests/test_redeploy_analytics.py",
    "tests/test_redeploy_capital_book.py",
    "tests/test_redeploy_capital_ledger.py",
    "tests/test_redeploy_governance_projection.py",
    "tests/test_redeploy_oversight.py",
    "tests/test_redeploy_phase13.py",
    "tests/test_redeploy_phase13_ui.py",
    "tests/test_redeploy_phase_a.py",
    "tests/test_redeploy_phase_c.py",
    "tests/test_redeploy_phase_e.py",
    "tests/test_redeploy_plan_engine.py",
    "tests/test_redeploy_semantic_integrity.py",
    "tests/test_redeploy_ui_tokens.py",
    "tests/test_reentry_cross_surface_v6.py",
    "tests/test_reentry_exit_cache.py",
    "tests/test_reentry_exit_universe_v4.py",
    "tests/test_reentry_intelligence_boards_v4.py",
    "tests/test_reentry_operator_controls_v5.py",
    "tests/test_reentry_resistance.py",
    "tests/test_reentry_rotation_alerts.py",
    "tests/test_reentry_rotation_v4_contract.py",
    "tests/test_reentry_shared_context_v1.py",
    "tests/test_reentry_visible_classification_data.py",
    "tests/test_reentry_watch_operator_contract.py",
    "tests/test_refresh_advisory_maturity_evidence.py",
    "tests/test_regime_cron1_risk_regime_freshness.py",
    "tests/test_release_logs_are_persistent.py",
    "tests/test_release_manifest_regenerated_clean.py",
    "tests/test_release_provenance.py",
    "tests/test_release_readiness.py",
    "tests/test_remediation_map_integrity.py",
    "tests/test_report_catalyst_gate.py",
    "tests/test_report_lineage.py",
    "tests/test_report_links.py",
    "tests/test_report_narrative.py",
    "tests/test_report_options_section.py",
    "tests/test_report_oversight.py",
    "tests/test_report_render.py",
    "tests/test_report_synthesis.py",
    "tests/test_reporting_engine.py",
    "tests/test_reprice_launcher_targets_served_tree.py",
    "tests/test_research_almanac.py",
    "tests/test_research_call_accounting.py",
    "tests/test_research_cpcv_paths.py",
    "tests/test_research_critique_pipeline.py",
    "tests/test_research_data_hygiene.py",
    "tests/test_research_durable_store.py",
    "tests/test_research_empirical.py",
    "tests/test_research_event_trigger.py",
    "tests/test_research_governance_acceptance.py",
    "tests/test_research_governance_adversarial.py",
    "tests/test_research_governance_cv.py",
    "tests/test_research_governance_deflated_sharpe.py",
    "tests/test_research_governance_enums_models.py",
    "tests/test_research_governance_final_adversarial.py",
    "tests/test_research_governance_last_mile_adversarial.py",
    "tests/test_research_governance_multiple_testing.py",
    "tests/test_research_governance_pbo.py",
    "tests/test_research_governance_pr_scope.py",
    "tests/test_research_governance_promotion_gate.py",
    "tests/test_research_governance_r1_final_adversarial.py",
    "tests/test_research_governance_reality_check.py",
    "tests/test_research_governance_retrieval_contract.py",
    "tests/test_research_governance_trial_registry.py",
    "tests/test_research_governance_v5_true_provenance.py",
    "tests/test_research_lane_health.py",
    "tests/test_research_lane_health_alert.py",
    "tests/test_research_mechanics_adversarial.py",
    "tests/test_research_mechanics_etf.py",
    "tests/test_research_mechanics_fixed_income.py",
    "tests/test_research_mechanics_valuation.py",
    "tests/test_research_metadata_contradiction.py",
    "tests/test_research_ops_flash_first_visibility.py",
    "tests/test_research_policy.py",
    "tests/test_research_r4_integration.py",
    "tests/test_research_scheduler_thesis_driven.py",
    "tests/test_research_skip_gate.py",
    "tests/test_research_thesis_delta.py",
    "tests/test_resolve_secret_tmpfs_precedence.py",
    "tests/test_risk_state_served_copy.py",
    "tests/test_rockville_live_foundation.py",
    "tests/test_rockville_watch_decision.py",
    "tests/test_ross_catalog_cross_video.py",
    "tests/test_ross_catalog_hermes.py",
    "tests/test_run_manual_endpoint_smoke.py",
    "tests/test_sale_event_detector.py",
    "tests/test_scalp_alert_emitter.py",
    "tests/test_scalp_alert_format.py",
    "tests/test_scalp_alert_labels.py",
    "tests/test_scalp_confirmations_gate.py",
    "tests/test_scalp_count1_current_run_counts.py",
    "tests/test_scalp_count1b_card_labels.py",
    "tests/test_scalp_data_tier_invariant.py",
    "tests/test_scalp_engine_isolation.py",
    "tests/test_scalp_ignition_scorer.py",
    "tests/test_scalp_lifecycle_funnel_report.py",
    "tests/test_scalp_lifecycle_maturity.py",
    "tests/test_scalp_lifecycle_maturity_regression.py",
    "tests/test_scalp_outcome_backfill.py",
    "tests/test_scalp_outcome_learning.py",
    "tests/test_scalp_session.py",
    "tests/test_scalp_setup_api.py",
    "tests/test_scalp_setup_detectors.py",
    "tests/test_scalp_setup_registry.py",
    "tests/test_scalp_t0_metrics.py",
    "tests/test_scalp_t1_metrics.py",
    "tests/test_scalp_trace_chain.py",
    "tests/test_scalp_trigger_engine.py",
    "tests/test_scalp_weight_refit.py",
    "tests/test_schd_advised_order_params.py",
    "tests/test_scheduled_agent_flash_canary.py",
    "tests/test_schwab_auth_failure_hardening.py",
    "tests/test_schwab_authenticator_page.py",
    "tests/test_schwab_enc_key_fallback.py",
    "tests/test_schwab_exec_parser.py",
    "tests/test_schwab_instrument_evidence.py",
    "tests/test_schwab_live_stops_sync.py",
    "tests/test_schwab_oco_bracket.py",
    "tests/test_schwab_protective_stop_2fa.py",
    "tests/test_schwab_token_refresh_http.py",
    "tests/test_scoring_empty_universe.py",
    "tests/test_screener_arch1_full_coverage.py",
    "tests/test_screener_arch2_full_ingestion_catalog.py",
    "tests/test_screener_arch2b_cap_overrides.py",
    "tests/test_screener_arch3_catalog_lifecycle.py",
    "tests/test_screener_arch3b_importer_membership_backfill.py",
    "tests/test_screener_arch3c_membership_lifecycle_api.py",
    "tests/test_screener_arch3d_falloff_lifecycle_apply.py",
    "tests/test_screener_arch4_full_universe_strategy_fit.py",
    "tests/test_screener_arch5_schedule_stale_remediation.py",
    "tests/test_screener_map1_strategy_coverage_repair.py",
    "tests/test_screener_map2_shadow_source_runs.py",
    "tests/test_screener_map3_promoter_family_thresholds.py",
    "tests/test_screener_map4_production_family_thresholds.py",
    "tests/test_screener_map5_dividend_income_scoring.py",
    "tests/test_sec_form4_momentum_context.py",
    "tests/test_secrets_admin_cookie_keys.py",
    "tests/test_secrets_render_deletion_guard.py",
    "tests/test_sector_leaders_join_contract.py",
    "tests/test_sector_leaders_service.py",
    "tests/test_sector_momentum_engine_v4.py",
    "tests/test_sector_momentum_notify.py",
    "tests/test_sector_research_universe.py",
    "tests/test_shadow_batch.py",
    "tests/test_sm_render_env.py",
    "tests/test_snaptrade_activity_ingest.py",
    "tests/test_snaptrade_protective_stop.py",
    "tests/test_social_awareness.py",
    "tests/test_social_route_persistence.py",
    "tests/test_social_route_policy.py",
    "tests/test_social_route_policy_replay.py",
    "tests/test_social_scalp_decision_alerts.py",
    "tests/test_social_scout_persistence.py",
    "tests/test_social_scout_pillars.py",
    "tests/test_social_scout_replay_report.py",
    "tests/test_social_scout_route_enforcement.py",
    "tests/test_social_scout_validation_block.py",
    "tests/test_social_traceability.py",
    "tests/test_sp1_strategy_proof_governance.py",
    "tests/test_sp2_strategy_watch_horizon_finviz_audit.py",
    "tests/test_sp2b_route_audit_repair.py",
    "tests/test_sp2c_route_audit_pipeline_wiring.py",
    "tests/test_squeeze_manual_review.py",
    "tests/test_stage_a_shadow_service.py",
    "tests/test_stage_b_blind_pass.py",
    "tests/test_stage_c_job_runner.py",
    "tests/test_stage_d_card_button.py",
    "tests/test_stop_alert_pl.py",
    "tests/test_stop_fixed_trailing_validation.py",
    "tests/test_stop_kind_pills.py",
    "tests/test_stop_kind_taxonomy.py",
    "tests/test_stop_management_decision_logic.py",
    "tests/test_stop_management_endpoint.py",
    "tests/test_stop_management_ui_hardening.py",
    "tests/test_stop_monitoring_health.py",
    "tests/test_stop_out_reentry_watch.py",
    "tests/test_stop_over_consensus_monitor.py",
    "tests/test_stop_policy.py",
    "tests/test_stop_replace_flow.py",
    "tests/test_stop_v20_backfill_tracking.py",
    "tests/test_stop_v21_reconciliation_engine.py",
    "tests/test_stop_v22_monitor_merge.py",
    "tests/test_stop_v23_strategy_trailing.py",
    "tests/test_stoplights_v3_integrity.py",
    "tests/test_store_consistency.py",
    "tests/test_strat_arch1_due_diligence.py",
    "tests/test_strategy_card_agent_rec.py",
    "tests/test_store_cadence.py",
    "tests/test_no_swallowed_alarms.py",
    "tests/test_alarm_imports_resolve.py",
    "tests/test_strategy_signal_sync_momentum_fallback.py",
    "tests/test_strategy_signal_sync_route_enforcement.py",
    "tests/test_strategy_ticket_quality_gate.py",
    "tests/test_strategy_ticket_reconciler_v11.py",
    "tests/test_strategy_ticket_review_contract.py",
    "tests/test_strategy_weekly_review_data_integrity.py",
    "tests/test_sweep_schwab_instruments.py",
    "tests/test_symbol_journey.py",
    "tests/test_symbol_thesis_canary_queue.py",
    "tests/test_symbol_thesis_coverage.py",
    "tests/test_symbol_thesis_integration.py",
    "tests/test_symbol_thesis_non_ticker_filter.py",
    "tests/test_symbol_thesis_queue_age.py",
    "tests/test_symbol_thesis_universe.py",
    "tests/test_symbol_volume_profile_builder.py",
    "tests/test_sync_cio_release_manifest_drive.py",
    "tests/test_system_health_youtube_freshness.py",
    "tests/test_telegram_alert_router_jun25.py",
    "tests/test_telegram_p0_card_gate.py",
    "tests/test_telegram_receipts_unify.py",
    "tests/test_thesis_decision_gate.py",
    "tests/test_thesis_mint_from_research.py",
    "tests/test_thesis_substantiveness.py",
    "tests/test_think_tank_prospect_discovery.py",
    "tests/test_ticker_alias.py",
    "tests/test_ticker_knowledge_graph.py",
    "tests/test_ticket_review_worker_fail_closed.py",
    "tests/test_tooling_guards.py",
    "tests/test_top_gainer_awareness.py",
    "tests/test_topic_ingestion_loop_break.py",
    "tests/test_tradingview_ingress_stub_r5.py",
    "tests/test_trail_lockin_threshold.py",
    "tests/test_trailing_limit_placement.py",
    "tests/test_transferson_universe.py",
    "tests/test_two_channel_approval.py",
    "tests/test_two_way_curation.py",
    "tests/test_two_way_reliability.py",
    "tests/test_ui_audit2_current_state_route_cleanup.py",
    "tests/test_universe_coverage.py",
    "tests/test_universe_projection_v1.py",
    "tests/test_validate_watch_quality_governance_from_ref.py",
    "tests/test_validation_sample_consistency.py",
    "tests/test_validation_taxonomy_audit.py",
    "tests/test_validation_taxonomy_compat.py",
    "tests/test_wake_ownership_and_freshness.py",
    "tests/test_warrior_tradeai_audit.py",
    "tests/test_watch2_watchpool_maturity_alerts.py",
    "tests/test_watch_canonical_quote.py",
    "tests/test_watch_decision_refresh_v5.py",
    "tests/test_watch_intelligence_unification.py",
    "tests/test_watch_packet_quality.py",
    "tests/test_watch_quality_audit_contract.py",
    "tests/test_watch_quality_gate3_contract.py",
    "tests/test_watch_quality_gate4_contract.py",
    "tests/test_watch_quality_gate5_contract.py",
    "tests/test_watch_quality_gate6_bound_contract.py",
    "tests/test_watch_quality_gate6_contract.py",
    "tests/test_watch_quality_policy.py",
    "tests/test_watch_quality_projection.py",
    "tests/test_watch_quality_projection_v2.py",
    "tests/test_watch_quality_rollout_orchestrator.py",
    "tests/test_watch_quality_scheduler_contract.py",
    "tests/test_watch_quality_ui_contract.py",
    "tests/test_watch_truthfulness_and_reentry_overlay_v1.py",
    "tests/test_watchlist_agent_jobs_offpeak.py",
    "tests/test_watchlist_intelligence.py",
    "tests/test_watchlist_lifecycle.py",
    "tests/test_watchlist_price_freshness.py",
    "tests/test_watchlist_priority.py",
    "tests/test_watchlist_propose_sizing.py",
    "tests/test_watchlist_remediation.py",
    "tests/test_watchlist_symbol_gate.py",
    "tests/test_watchlist_volatility.py",
    "tests/test_weekly_learning_api.py",
    "tests/test_workflow_id_propagation.py",
    "tests/test_youtube_channel_discovery_asset_classes.py",
    "tests/test_youtube_transcript_ingest_quota.py",
])


def all_test_files() -> set[str]:
    return {
        str(p.relative_to(REPO))
        for p in TESTS.rglob("test_*.py")
        if "__pycache__" not in str(p)
    }


def gated_files() -> set[str]:
    """Files named by the hardening runner's GATES, read from source."""
    sys.path.insert(0, str(REPO / "scripts"))
    try:
        import run_cio_hardening_ci as runner
    except Exception:
        return set()
    out: set[str] = set()
    for _name, paths in getattr(runner, "GATES", []):
        out.update(paths)
    return out


def audit() -> dict:
    every = all_test_files()
    gated = gated_files() & every
    denied = set(DENY) & every
    unlisted = sorted(every - gated - denied)
    from_baseline = [f for f in unlisted if f in UNLISTED_BASELINE]
    new = [f for f in unlisted if f not in UNLISTED_BASELINE]
    resolved = sorted(set(UNLISTED_BASELINE) - set(unlisted) - (set(UNLISTED_BASELINE) - every))
    return {
        "schema": SCHEMA,
        "authority": "READ_ONLY_ADVISORY",
        "test_files": len(every),
        "run_by_ci": len(gated),
        "denied": len(denied),
        "unlisted": len(unlisted),
        "unlisted_inherited": len(from_baseline),
        "unlisted_new": new,
        "coverage_pct": round(100.0 * len(gated) / max(len(every), 1), 1),
        "resolved_since_baseline": resolved,
        "ok": not new,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="Fail on a NEW test file CI does not run")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--fail-on-new", action="store_true")
    args = ap.parse_args()
    r = audit()

    if args.json:
        print(json.dumps(r, indent=2, sort_keys=True))
    else:
        print(f"test files              : {r['test_files']}")
        print(f"  run by CI             : {r['run_by_ci']}  ({r['coverage_pct']}%)")
        print(f"  denied, with reason   : {r['denied']}")
        print(f"  unlisted (inherited)  : {r['unlisted_inherited']}")
        print(f"  unlisted (NEW)        : {len(r['unlisted_new'])}")
        for f in r["unlisted_new"][:20]:
            print(f"    ✗ {f}")
        if r["resolved_since_baseline"]:
            print(f"\n  now run by CI since baseline ({len(r['resolved_since_baseline'])}):")
            for f in r["resolved_since_baseline"][:10]:
                print(f"    ✓ {f}")

    if args.fail_on_new and r["unlisted_new"]:
        print("\nFAIL: a new test file is not run by CI and not explained.\n"
              "Add it to a gate in scripts/run_cio_hardening_ci.py, or to DENY here\n"
              "with the reason it cannot be collected.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
