#!/usr/bin/env node
// Generate the MetricGuideKey union from assets/ui_metric_guide.yaml (PR3, 2026-09-27).
// No YAML dependency: the file is written in a strict subset (`entries:` then two-space
// indented `key:` lines), and scripts/lib/ui_metric_guide.py validates the full document in CI.
//   node scripts/gen_metric_guide_keys.mjs           # writes the .generated.ts
//   node scripts/gen_metric_guide_keys.mjs --check   # fails when the file is stale (runs in npm build)
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..')
const YAML = path.join(ROOT, 'assets/ui_metric_guide.yaml')
const OUT = path.join(ROOT, 'apps/command-center-v3/src/lib/metricGuide.keys.generated.ts')
const CHECK = process.argv.includes('--check')

const src = fs.readFileSync(YAML, 'utf8')
const version = (src.match(/^version:\s*(\S+)/m) || [])[1] || '0'
const keys = []
let inEntries = false
for (const line of src.split('\n')) {
  if (/^entries:\s*$/.test(line)) { inEntries = true; continue }
  if (!inEntries) continue
  const m = line.match(/^  ([A-Za-z0-9_.\-]+):\s*$/)
  if (m) keys.push(m[1])
}
keys.sort()
if (!keys.length) { console.error('gen_metric_guide_keys: no entries found'); process.exit(1) }
const body = [
  '// GENERATED by scripts/gen_metric_guide_keys.mjs from assets/ui_metric_guide.yaml — do not edit.',
  `// version ${version} · ${keys.length} keys`,
  'export const METRIC_GUIDE_VERSION = ' + JSON.stringify(String(version)),
  'export const METRIC_GUIDE_KEYS = [',
  ...keys.map(k => `  ${JSON.stringify(k)},`),
  '] as const',
  'export type MetricGuideKey = (typeof METRIC_GUIDE_KEYS)[number]',
  '',
].join('\n')
if (CHECK) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
  if (cur !== body) { console.error(`gen_metric_guide_keys: ${path.relative(ROOT, OUT)} is stale — run node scripts/gen_metric_guide_keys.mjs`); process.exit(1) }
  console.log(`[metric-guide] keys current (${keys.length})`)
} else {
  fs.writeFileSync(OUT, body)
  console.log(`[metric-guide] wrote ${path.relative(ROOT, OUT)} (${keys.length} keys)`)
}
