#!/usr/bin/env python3
"""generate_state_of_repo_snapshot.py — STATE_OF_REPO_LATEST.md generator (READ-ONLY).

Produces docs/project/STATE_OF_REPO_LATEST.md from git + .env + the runtime inventory + (optional)
DB. Degrades gracefully to "unknown" when DB / files are unavailable. Mutates no runtime state.
"""
import json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "project", "STATE_OF_REPO_LATEST.md")
INV = os.path.join(ROOT, "data", "runtime", "runtime_job_inventory_latest.json")

PIPELINES = ["tradeai-market-pipeline", "tradeai-after-close-pipeline", "hermes-advisory-pipeline",
             "hermes-research-pipeline", "llm-control-pipeline", "governance-pipeline",
             "portfolio-maintenance-pipeline"]


def sh(cmd):
    try:
        return subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=20, cwd=ROOT).stdout.strip()
    except Exception:
        return ""


def env_val(key, default="unknown"):
    try:
        for line in open(os.path.join(ROOT, ".env")):
            if line.strip().startswith(f"{key}="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    except Exception:
        pass
    return default


def db_facts():
    facts = {"live_trading_allowed": "unknown", "atm_mode": "unknown",
             "llm_queue_pending": "unknown", "hermes_last_write_min": "unknown",
             "closed_trades": "unknown"}
    try:
        import psycopg2
        c = psycopg2.connect(host=os.environ.get("DB_HOST", "localhost"),
                             port=os.environ.get("DB_PORT", "5432"),
                             dbname=os.environ.get("DB_NAME", "trade_ai"),
                             user=os.environ.get("DB_USER", "trade_ai"),
                             password=os.environ.get("DB_PASSWORD", ""))
        cur = c.cursor()
        def q(sql, d="unknown"):
            try:
                cur.execute(sql); r = cur.fetchone(); return r[0] if r else d
            except Exception:
                c.rollback(); return d
        facts["live_trading_allowed"] = q("SELECT live_trading_allowed FROM paper_validation_policy WHERE active=true")
        facts["atm_mode"] = q("SELECT mode FROM atm_state WHERE id=1")
        facts["llm_queue_pending"] = q("SELECT count(*) FROM deep_overnight_llm_queue WHERE status='pending'")
        facts["hermes_last_write_min"] = q("SELECT round(extract(epoch from(now()-max(created_at)))/60.0,1) FROM hermes_research_intelligence")
        facts["closed_trades"] = q("SELECT count(*) FROM paper_trades WHERE status IN ('closed','CLOSED') AND pnl IS NOT NULL")
        c.close()
    except Exception:
        pass
    return facts


def main():
    # load env into os.environ for DB
    try:
        for line in open(os.path.join(ROOT, ".env")):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1); os.environ.setdefault(k, v.strip().strip('"').strip("'"))
    except Exception:
        pass

    branch = sh("git branch --show-current") or "unknown"
    commits = sh("git log -5 --oneline") or "unknown"
    dirty = sh("git status --porcelain | wc -l") or "unknown"
    phase_docs = sorted(re.findall(r"PHASE\d+\w*", " ".join(os.listdir(os.path.join(ROOT, "docs", "architecture")))
                                   if os.path.isdir(os.path.join(ROOT, "docs", "architecture")) else ""))
    latest_phase = phase_docs[-1] if phase_docs else "unknown"

    inv = json.load(open(INV)) if os.path.exists(INV) else {}
    s = inv.get("summary", {})
    f = db_facts()
    alpaca_mode = env_val("ALPACA_MODE", "paper")

    L = []
    L.append("# State of Repo — LATEST\n")
    L.append("Auto-generated by `scripts/generate_state_of_repo_snapshot.py` (read-only; DB facts "
             "degrade to 'unknown' if unavailable).\n")
    L.append("## Git")
    L.append(f"- Branch: **{branch}**")
    L.append(f"- Dirty files: {dirty}")
    L.append("- Latest commits:")
    for ln in commits.splitlines():
        L.append(f"  - `{ln}`")
    L.append(f"\n## Phase\n- Latest architecture phase doc: **{latest_phase}**")
    L.append("- Current: Phase 199 — Runtime Control Plane Consolidation + v3 Canonical UI Governance")
    L.append("\n## Safety state")
    L.append(f"- **Paper trading mode:** ALPACA_MODE=`{alpaca_mode}`")
    L.append(f"- **Live trading:** `live_trading_allowed`={f['live_trading_allowed']} → **PROHIBITED / OFF**")
    L.append("- **Live Alpaca endpoint:** BLOCKED")
    L.append("- **Level 7:** PROHIBITED (no flag present)")
    L.append(f"- ATM mode (paper auto-approver): {f['atm_mode']}")
    L.append("- **Protection workstream:** PAUSED (until advised trades close) — observe-only")
    L.append("- **Threshold tuning:** OBSERVE-ONLY")
    L.append("\n## Runtime control plane")
    L.append(f"- Cron lines: {s.get('total_cron_lines','unknown')} · services: {s.get('total_systemd_services','unknown')} · "
             f"timers: {s.get('total_systemd_timers','unknown')} · unique scripts: {s.get('unique_scripts','unknown')} · "
             f"multi-scheduled: {len(s.get('duplicate_scripts',{}))}")
    L.append("- Target pipelines (199C):")
    for p in PIPELINES:
        L.append(f"  - {p}")
    L.append("- Pipeline controllers: dry-run skeletons in `scripts/pipelines/` (no schedules wired)")
    L.append(f"\n## LLM queue\n- deep_overnight_llm_queue pending: {f['llm_queue_pending']}")
    L.append(f"\n## Hermes research\n- Last write: {f['hermes_last_write_min']} min ago (24/7 expected)")
    L.append("\n## Blockers / gate")
    L.append(f"- Live-trading gate: closed_trades {f['closed_trades']}/100 (+ days/win/PF) — **BLOCKED** by design")
    L.append("\n## Next triggers")
    L.append("- Pipeline cadences unchanged this phase; freshness monitor `*/20`, watchdog `*/30`")
    L.append("\n## Governance reminders")
    L.append("- **v3 is canonical** for all new UI. v2 is frozen/reference (`/api/v2` = backend namespace, not v2 UI).")
    L.append("- **Drive sync:** run `bash scripts/sync-docs-to-drive.sh` after doc changes.")
    L.append("- No crons disabled without explicit operator approval.")
    L.append("\n---\n*Read-only snapshot; no runtime mutation.*")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fp:
        fp.write("\n".join(L) + "\n")
    print(f"[state-of-repo] wrote {OUT} (branch={branch}, dirty={dirty}, live_allowed={f['live_trading_allowed']})")


if __name__ == "__main__":
    main()
