#!/usr/bin/env bash
# regenerate_system_facts.sh — refresh SYSTEM_FACTS_LATEST.md from live introspection.
# Referenced by docs/operations/DOCUMENTATION_STANDARDS.md
# Do NOT edit SYSTEM_FACTS_LATEST.md by hand — use this script.

set -euo pipefail

PROJECT_ROOT="/home/johnclaw/trade-ai-v12-rebuild/trade-ai-v12-rebuild"
cd "$PROJECT_ROOT"

# Holdings guard
HOLDINGS=$(python3 -c "
import json
d = json.load(open('data/portfolios/state/holdings.json'))
assert d['portfolio_totals']['total_value'] > 1_000_000
print(f\"\${d['portfolio_totals']['total_value']:,.2f}\")")

# Live counts (targeted grep for DB password, not source .env)
DBPW=$(grep '^DB_PASSWORD=' .env | head -1 | cut -d= -f2)
TABLES=$(PGPASSWORD=$DBPW psql -h localhost -U trade_ai -d trade_ai -tAc \
  "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public';")
SCRIPTS=$(find scripts -name "*.py" -type f | wc -l)
CRONS=$(crontab -l | grep -v "^#" | grep -v "^$" | wc -l)
PAGES=$(find apps/command-center-v2/src/pages -name "*.tsx" 2>/dev/null | wc -l)
STRATEGIES=$(ls config/strategies/*.yaml 2>/dev/null | wc -l)
EMBEDDINGS=$(PGPASSWORD=$DBPW psql -h localhost -U trade_ai -d trade_ai -tAc \
  "SELECT COUNT(*) FROM content_embeddings;" 2>/dev/null || echo "?")
RECENT_COMMITS=$(git log --oneline -5 | sed 's/^/- /')

# Write to both locations for compatibility
for TARGET in docs/project/SYSTEM_FACTS_LATEST.md docs/current_state/SYSTEM_FACTS_LATEST.md; do
  mkdir -p "$(dirname "$TARGET")"
  cat > "$TARGET" << FACTS_EOF
# System Facts (Latest)

Generated: $(date +"%Y-%m-%d %H:%M %Z")
Source: Live introspection on ms01-openclaw
Regeneration: \`bash scripts/regenerate_system_facts.sh\`

---

## Current Counts

| Metric | Value |
|--------|-------|
| Portfolio value | ${HOLDINGS} |
| PostgreSQL tables | ${TABLES} |
| Python scripts | ${SCRIPTS} |
| Active cron entries | ${CRONS} |
| React pages | ${PAGES} |
| Strategy YAMLs | ${STRATEGIES} |
| Content embeddings | ${EMBEDDINGS} |

---

## Recent Commits

${RECENT_COMMITS}

---

## Notes

- This file is regenerated by \`scripts/regenerate_system_facts.sh\`
- DO NOT edit by hand — changes will be overwritten
- Run regeneration whenever counts change materially
FACTS_EOF
done

echo "SYSTEM_FACTS_LATEST.md regenerated"
echo "Tables: ${TABLES} | Scripts: ${SCRIPTS} | Crons: ${CRONS} | Pages: ${PAGES}"
echo "Strategies: ${STRATEGIES} | Embeddings: ${EMBEDDINGS}"
