#!/usr/bin/env python3
"""report_docs_inventory.py — Inventory and classify local docs.

Read-only by default (no moves/deletes). No trading changes.

Also the **documentation index generator**: write or drift-check the committed
``docs/INDEX.md``. Hand-maintained ``docs/project/PROJECT_DOC_INDEX.md`` and
``docs/DOCUMENTATION_INDEX.md`` remain; this does not replace them with a third
narrative index — it wires *this* inventory into a regenerable tree listing.

Usage:
    python3 scripts/report_docs_inventory.py --root docs --verbose
    python3 scripts/report_docs_inventory.py --write-index
    python3 scripts/report_docs_inventory.py --check-index
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJ = Path(__file__).resolve().parent.parent

INDEX_RELPATH = "docs/INDEX.md"
INDEX_PATH = PROJ / INDEX_RELPATH

# Active canonical docs that must NEVER be archived/deleted
ACTIVE_KEEP = {
    "docs/A1A.md", "docs/MASTER_SYSTEM_DOCUMENTATION.md", "docs/ARCHITECTURE_OVERVIEW.md",
    "docs/RESTORE_GUIDE.md", "docs/CHEAT_SHEET.md", "docs/v4_1_deployment_log.md",
    "docs/LLM_FLEET_STRATEGY_v4_1_FINAL.md", "docs/CLAUDE_CODE_EXECUTION_PROMPT_LLM_v4_1_FINAL.md",
    "docs/OPERATOR_RUNBOOK_LLM_v4_1_FINAL.md", "docs/project/PROJECT_DOC_INDEX.md",
}
ACTIVE_FOLDERS = {
    "docs/execution_safety/", "docs/recovery/", "docs/maturity_hardening/",
    "docs/project/", "docs/strategy/", "docs/generated/", "docs/design/",
}
ARCHIVE_PATTERNS = [
    r"\.bak", r"bak_", r"_backup", r"superseded", r"_old\b",
    r"V[56789]\.", r"v[2-4]\.\d", r"_pre_", r"_20260[34]",
]
ARTIFACT_EXTS = {".py", ".ts", ".tsx", ".css", ".xlsx", ".mmd", ".txt", ".sh"}
CODE_IN_DOCS = {".py", ".ts", ".tsx", ".css", ".sh"}

# Structured doc header = YAML front matter or bold metadata in the first N lines.
# Docs lacking this are counted as MISSING HEADER — the honest documentation debt.
HEADER_SCAN_LINES = 40
HEADER_PATTERNS = (
    re.compile(r"(?i)^\*\*Status:\*\*"),
    re.compile(r"(?i)^\*\*Created:\*\*"),
    re.compile(r"(?i)^\*\*Updated:\*\*"),
    re.compile(r"(?i)^\*\*Last updated:\*\*"),
    re.compile(r"(?i)^\*\*Authority:\*\*"),
    re.compile(r"(?i)^\*\*Owner:\*\*"),
    re.compile(r"(?i)^\*\*Date:\*\*"),
    re.compile(r"(?i)^\*\*Document version:\*\*"),
    re.compile(r"(?i)^Status:\s*\S"),
    re.compile(r"(?i)^Authority:\s*\S"),
    re.compile(r"(?i)^as_of\s*:"),
    re.compile(r"(?i)^\*\*as_of\*\*"),
    re.compile(r"(?i)^doc-version\s*:"),
)

HEADER_OK = "OK"
HEADER_MISSING = "MISSING HEADER"
HEADER_NA = "N/A"

GENERATOR_BANNER = (
    "<!-- GENERATED by scripts/report_docs_inventory.py — do not hand-edit. "
    "Regenerate: python3 scripts/report_docs_inventory.py --write-index -->"
)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def classify(relpath: str, ext: str, size: int):
    rp = relpath.lower()

    if relpath in ACTIVE_KEEP:
        return "active_keep", "canonical active doc", "high"
    for af in ACTIVE_FOLDERS:
        if relpath.startswith(af):
            return "current_phase_keep", f"in active folder {af}", "high"
    if "00_README.md" in relpath:
        return "current_phase_keep", "phase readme", "high"

    for pat in ARCHIVE_PATTERNS:
        if re.search(pat, rp):
            return "archive_superseded", f"matches pattern {pat}", "medium"

    if "_archive/" in rp or "/archive/" in rp:
        return "archive_superseded", "already in archive folder", "high"

    if ext in CODE_IN_DOCS:
        return "artifact_code_snapshot", f"code file ({ext}) in docs", "medium"

    if ext in ARTIFACT_EXTS and ext not in {".md", ".json", ".yaml", ".yml"}:
        return "artifact_raw_sync", f"non-doc extension {ext}", "low"

    if re.search(r"session[_\s]*\d+", rp, re.I):
        return "archive_session_handoff", "session handoff doc", "medium"

    if any(x in rp for x in ["blueprint", "marl_blueprint", "classification_rule_engine"]):
        return "archive_legacy_blueprint", "legacy blueprint", "medium"

    return "review_required", "not classified", "low"


def has_structured_header(text: str) -> bool:
    """True when the doc carries YAML front matter or bold metadata keys."""
    if text.startswith("---"):
        # YAML front matter: opening --- ... closing --- within the scan window
        rest = text[3:]
        end = rest.find("\n---")
        if end != -1 and end < 4000:
            return True
    head_lines = text.splitlines()[:HEADER_SCAN_LINES]
    for line in head_lines:
        s = line.strip()
        for pat in HEADER_PATTERNS:
            if pat.search(s):
                return True
    return False


def extract_title(text: str, fallback: str) -> str:
    for line in text.splitlines()[:80]:
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip() or fallback
    return fallback


def header_status_for(path: Path, ext: str) -> tuple[str, str | None]:
    """Return (header_status, title_or_None)."""
    if ext != ".md":
        return HEADER_NA, None
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return HEADER_MISSING, None
    title = extract_title(text, path.name)
    if has_structured_header(text):
        return HEADER_OK, title
    return HEADER_MISSING, title


def _candidate_files(root: Path) -> list[Path]:
    """Files under `root` that git tracks, falling back to a filesystem walk.

    WHY THIS IS GIT-AWARE. This previously used `root.rglob("*")`, a plain
    filesystem walk with no knowledge of git. The index it generates is checked by
    a REQUIRED CI gate (docs_index_drift), and CI runs on a clean checkout that
    contains only tracked files. Any developer with build artifacts under docs/ --
    a single docs/_design/.../__pycache__/ was enough -- therefore regenerated a
    different index than CI could ever reproduce:

        tracked docs     2274   (what CI sees, and what was committed)
        filesystem walk  2276   (two gitignored .pyc files)

    That divergence produced a red gate on commits that passed locally, and a
    "fix" regenerated from the polluted tree turned a green PR red. It caused the
    index thrash across two nights.

    Tracked-file listing is the shape that matches the gate. The fallback keeps
    the tool usable outside a git checkout, where there is nothing to diverge from.
    """
    try:
        out = subprocess.run(
            ["git", "-C", str(PROJ), "ls-files", "-z", "--", str(root)],
            capture_output=True, check=True, timeout=60,
        ).stdout.decode("utf-8", "replace")
        names = [n for n in out.split("\0") if n]
        if names:
            return [PROJ / n for n in names]
    except (OSError, subprocess.SubprocessError):
        pass
    # Not a git checkout (or git unavailable): fall back to the filesystem.
    return list(root.rglob("*"))


def collect_inventory(root: Path) -> tuple[list[dict], dict]:
    inventory: list[dict] = []
    hash_groups: dict[str, list[str]] = {}
    root = Path(root)
    if not root.is_absolute():
        root = (PROJ / root).resolve()
    else:
        root = root.resolve()

    for filepath in sorted(_candidate_files(root)):
        if not filepath.is_file():
            continue
        relpath = str(filepath.relative_to(PROJ)).replace("\\", "/")
        ext = filepath.suffix.lower()
        size = filepath.stat().st_size
        mtime = datetime.fromtimestamp(
            filepath.stat().st_mtime, tz=timezone.utc
        ).isoformat()
        fhash = sha256(filepath)
        status, reason, confidence = classify(relpath, ext, size)
        h_status, title = header_status_for(filepath, ext)

        entry = {
            "path": relpath,
            "filename": filepath.name,
            "ext": ext,
            "size": size,
            "mtime": mtime,
            "sha256": fhash,
            "status_guess": status,
            "reason": reason,
            "confidence": confidence,
            "header_status": h_status,
        }
        if title is not None:
            entry["title"] = title
        inventory.append(entry)
        hash_groups.setdefault(fhash, []).append(relpath)

    for entry in inventory:
        group = hash_groups.get(entry["sha256"], [])
        if len(group) > 1:
            entry["duplicate_count"] = len(group)
            entry["duplicate_group"] = group
            if entry["status_guess"] == "review_required":
                entry["status_guess"] = "delete_candidate_duplicate"
                entry["reason"] = f"byte-identical with {len(group)-1} other file(s)"

    # INDEX.md is generated from this inventory — exclude it from all INDEX
    # metrics so --write-index and --check-index agree whether or not it exists.
    indexed = [e for e in inventory if e["path"] != INDEX_RELPATH]
    by_status: dict[str, int] = {}
    for e in indexed:
        by_status[e["status_guess"]] = by_status.get(e["status_guess"], 0) + 1

    md_entries = [e for e in indexed if e["ext"] == ".md"]
    missing_header = sum(1 for e in md_entries if e["header_status"] == HEADER_MISSING)
    dup_groups = sum(1 for g in hash_groups.values() if len([p for p in g if p != INDEX_RELPATH]) > 1)

    summary = {
        "total": len(indexed),
        "by_status": by_status,
        "duplicate_groups": dup_groups,
        "markdown_total": len(md_entries),
        "missing_header": missing_header,
        "header_label": HEADER_MISSING,
    }
    return inventory, summary


def tree_fingerprint(inventory: list[dict]) -> str:
    """Content-only fingerprint (excludes INDEX.md and wall-clock fields)."""
    lines = []
    for e in inventory:
        if e["path"] == INDEX_RELPATH:
            continue
        lines.append(
            f"{e['path']}\t{e['sha256']}\t{e['status_guess']}\t{e['header_status']}"
        )
    blob = "\n".join(lines).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()


def render_index_md(inventory: list[dict], summary: dict) -> str:
    """Deterministic INDEX.md body — no wall-clock as_of (avoids spurious drift)."""
    fp = tree_fingerprint(inventory)
    rows = [
        e for e in inventory
        if e["ext"] == ".md" and e["path"] != INDEX_RELPATH
    ]
    rows.sort(key=lambda e: e["path"])

    by_header = {HEADER_OK: 0, HEADER_MISSING: 0}
    for e in rows:
        by_header[e["header_status"]] = by_header.get(e["header_status"], 0) + 1

    lines = [
        GENERATOR_BANNER,
        "# Docs Index",
        "",
        "**Generator:** `python3 scripts/report_docs_inventory.py --write-index`",
        f"**Tree fingerprint:** `{fp}`",
        "",
        "Hand-maintained narrative indexes remain authoritative for *what is current*:",
        "`docs/DOCUMENTATION_INDEX.md`, `docs/project/PROJECT_DOC_INDEX.md`.",
        "This file is the regenerable tree listing from `report_docs_inventory.py`.",
        "",
        "## Counts",
        "",
        "| Metric | Count |",
        "|--------|------:|",
        f"| Files under `docs/` (excl. this INDEX) | {summary['total']} |",
        f"| Markdown (excl. this INDEX) | {summary['markdown_total']} |",
        f"| **{HEADER_MISSING}** | **{summary['missing_header']}** |",
        f"| Header OK | {by_header.get(HEADER_OK, 0)} |",
        f"| Duplicate groups | {summary['duplicate_groups']} |",
        "",
        "### By status_guess",
        "",
        "| Status | Count |",
        "|--------|------:|",
    ]
    for s, c in sorted(summary["by_status"].items()):
        lines.append(f"| {s} | {c} |")

    lines.extend([
        "",
        "## Markdown tree",
        "",
        "| Path | Title | status_guess | header | sha12 |",
        "|------|-------|--------------|--------|------|",
    ])
    for e in rows:
        title = (e.get("title") or e["filename"]).replace("|", "\\|")
        path = e["path"]
        lines.append(
            f"| `{path}` | {title} | {e['status_guess']} | {e['header_status']} | "
            f"`{e['sha256'][:12]}` |"
        )
    lines.append("")
    return "\n".join(lines)


def write_index(inventory: list[dict], summary: dict) -> Path:
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    text = render_index_md(inventory, summary)
    INDEX_PATH.write_text(text, encoding="utf-8")
    return INDEX_PATH


def check_index(inventory: list[dict], summary: dict) -> int:
    expected = render_index_md(inventory, summary)
    if not INDEX_PATH.is_file():
        print(f"[FAIL] {INDEX_RELPATH} missing — run with --write-index", file=sys.stderr)
        return 1
    actual = INDEX_PATH.read_text(encoding="utf-8")
    if actual == expected:
        print(
            f"[PASS] {INDEX_RELPATH} matches inventory "
            f"(MISSING HEADER={summary['missing_header']}, "
            f"md={summary['markdown_total']}, fingerprint={tree_fingerprint(inventory)[:12]})"
        )
        return 0
    import difflib
    diff = "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"a/{INDEX_RELPATH}",
            tofile=f"b/{INDEX_RELPATH} (regenerated)",
            n=3,
        )
    )
    # The index is built from `git ls-files`, so a NEW doc that is still
    # untracked is invisible to --write-index: regenerating before `git add`
    # produces an index that passes locally and drifts the moment the file is
    # committed. Say so here, because the obvious reading of "regenerate" is to
    # do it again in the same wrong order.
    print(f"[FAIL] {INDEX_RELPATH} drift — regenerate with --write-index "
          "AFTER `git add` (the index is built from git ls-files, so untracked "
          "docs are not in it yet)", file=sys.stderr)
    print(diff[:4000], file=sys.stderr)
    if len(diff) > 4000:
        print(f"... diff truncated ({len(diff)} bytes total)", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Docs inventory + INDEX.md generator")
    p.add_argument("--root", default="docs")
    p.add_argument("--output-json", type=str)
    p.add_argument("--output-md", type=str)
    p.add_argument("--write-index", action="store_true",
                   help=f"Write regenerable {INDEX_RELPATH}")
    p.add_argument("--check-index", action="store_true",
                   help=f"Regenerate {INDEX_RELPATH} in-memory and fail on drift")
    p.add_argument("--verbose", action="store_true")
    args = p.parse_args(argv)

    root = PROJ / args.root
    if not root.is_dir():
        print(f"root not found: {root}", file=sys.stderr)
        return 2

    inventory, summary = collect_inventory(root)

    if args.verbose or not (args.write_index or args.check_index or args.output_json or args.output_md):
        print(f"Docs Inventory: {summary['total']} files")
        for status, count in sorted(summary["by_status"].items()):
            print(f"  {status}: {count}")
        print(f"  Duplicate groups: {summary['duplicate_groups']}")
        print(f"  Markdown (excl. INDEX): {summary['markdown_total']}")
        print(f"  {HEADER_MISSING}: {summary['missing_header']}")

    if args.output_json:
        Path(args.output_json).write_text(
            json.dumps({"summary": summary, "inventory": inventory}, indent=2, default=str),
            encoding="utf-8",
        )
    if args.output_md:
        md = [
            f"# Docs Inventory — {summary['total']} files",
            "",
            f"**{HEADER_MISSING}:** {summary['missing_header']}",
            "",
            "| Status | Count |",
            "|--------|-------|",
        ]
        for s, c in sorted(summary["by_status"].items()):
            md.append(f"| {s} | {c} |")
        md.append(f"\n## Duplicate groups: {summary['duplicate_groups']}")
        Path(args.output_md).write_text("\n".join(md), encoding="utf-8")

    rc = 0
    if args.write_index:
        path = write_index(inventory, summary)
        print(
            f"Wrote {path.relative_to(PROJ)} "
            f"(MISSING HEADER={summary['missing_header']}, "
            f"fingerprint={tree_fingerprint(inventory)[:12]})"
        )
    if args.check_index:
        # Re-collect so a just-written INDEX is not required for fingerprint stability
        # (INDEX is excluded from fingerprint / rows).
        rc = check_index(inventory, summary) or rc

    return rc


if __name__ == "__main__":
    raise SystemExit(main())
