-- Rollback SQL for classifier batch2 interruption audit
-- Generated 2026-05-28
--
-- RESULT: No rollback needed.
-- Batch2 updated 0 rows in strategy_backtest_trades.
-- All symbols were already classified in batch1.
-- The 3 successful LLM calls (AXTI, APAM, ADBE) found 0 rows to update.
-- The remaining 27 trades errored due to Ollama connection refused.
--
-- This file exists for audit completeness only.
-- No SQL statements to execute.
