#!/usr/bin/env python3
"""Provision the production m2_agent role credential without it ever being typed.

Companion to ensure_shadow_rw_dsn.py. That script targets the LAB database and
refuses production; this one targets production `trade_ai` deliberately, for the
M2 bitemporal cognitive-memory cutover.

The difference that shapes this script: CREATE ROLE and CREATE EXTENSION need
superuser, which this process does not have. So it cannot do the DDL itself.
Instead it generates the password, makes Bitwarden SM the source of truth, and
emits a 0600 SQL file the operator pipes into a superuser psql. The password is
never printed, never echoed to a terminal, and never enters shell history.

Flow:
  1) Generate a 40-char password (secrets.choice, never displayed)
  2) Build postgresql://m2_agent:<pw>@<host>:<port>/trade_ai from DB_* env
  3) Upsert SM secret M2_AGENT_DSN via secrets_admin.set_secret, then
     render_env --now so /run/user/<uid>/tradeai/env picks it up
  4) Write CREATE EXTENSION + CREATE ROLE to a 0600 file under the runtime dir
  5) Operator runs:  sudo -u postgres psql -d trade_ai -f <file>
     then:           ensure_m2_agent_dsn.py --verify --shred
  6) Print ONLY: ok/fail, action, secret_upserted, dsn_len, sql_path
     NEVER the password or the full DSN

SM is upserted BEFORE the role exists on purpose: it is the record of the
password, and the SQL file is derived from it. If the operator never runs the
SQL, --verify reports role_exists false rather than the secret silently
describing a role that is not there.

Usage:
  .venv/bin/python scripts/secrets/ensure_m2_agent_dsn.py --dry-run
  .venv/bin/python scripts/secrets/ensure_m2_agent_dsn.py
  sudo -u postgres psql -d trade_ai -f /run/user/$(id -u)/tradeai/m2_agent_role.sql
  .venv/bin/python scripts/secrets/ensure_m2_agent_dsn.py --verify --shred

This script performs NO DDL and NO write to production. It only reads catalog
tables to verify, and writes to Bitwarden SM plus one 0600 local file.
"""
from __future__ import annotations

import argparse
import json
import os
import secrets
import string
import subprocess
import sys
from pathlib import Path
from typing import Any
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "scripts" / "secrets"))

ROLE = "m2_agent"
SECRET_NAME = "M2_AGENT_DSN"
PRODUCTION_DB = "trade_ai"
SHADOW_LITERAL = "m2agent"  # the isolated container's throwaway; never reuse it
RUNTIME_DIR = Path(f"/run/user/{os.getuid()}/tradeai")
SQL_PATH = RUNTIME_DIR / "m2_agent_role.sql"


def _gen_password(n: int = 40) -> str:
    """Letters+digits only: the value lands in a DSN, and escaping punctuation
    through a URL, a SQL literal and an EnvironmentFile is three chances to get
    it wrong. 40 chars of [A-Za-z0-9] is ~238 bits."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(n))


def _db_params() -> dict[str, str]:
    """Production connection parameters from env, falling back to the repo .env.
    Only host/port/dbname are used to compose the DSN; DB_PASSWORD is not read."""
    env: dict[str, str] = {}
    for k in ("DB_HOST", "DB_PORT", "DB_NAME"):
        v = os.environ.get(k)
        if v:
            env[k] = v
    dotenv = ROOT / ".env"
    if dotenv.exists():
        for line in dotenv.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                k, v = line.split("=", 1)
                k = k.strip()
                if k in ("DB_HOST", "DB_PORT", "DB_NAME"):
                    env.setdefault(k, v.strip())
    return {
        "host": env.get("DB_HOST", "localhost"),
        "port": env.get("DB_PORT", "5432"),
        "dbname": env.get("DB_NAME", PRODUCTION_DB),
    }


def _build_dsn(parts: dict[str, str], password: str) -> str:
    return (
        f"postgresql://{ROLE}:{quote(password, safe='')}"
        f"@{parts['host']}:{parts['port']}/{parts['dbname']}"
    )


def _sql_text(password: str) -> str:
    """Idempotent: creates the role, or resets its password if it already exists,
    so a re-run after a partial apply converges instead of erroring."""
    lit = password.replace("'", "''")
    return f"""-- Generated by scripts/secrets/ensure_m2_agent_dsn.py — DELETE AFTER RUNNING.
-- Contains a live credential. Mode 0600, on tmpfs. Run as superuser:
--     sudo -u postgres psql -d {PRODUCTION_DB} -f {SQL_PATH}
-- then shred it:
--     scripts/secrets/ensure_m2_agent_dsn.py --verify --shred

CREATE EXTENSION IF NOT EXISTS vector;

DO $ensure_m2_agent$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{ROLE}') THEN
    ALTER ROLE {ROLE} WITH LOGIN PASSWORD '{lit}'
      NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    RAISE NOTICE 'role {ROLE}: password reset';
  ELSE
    CREATE ROLE {ROLE} LOGIN PASSWORD '{lit}'
      NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    RAISE NOTICE 'role {ROLE}: created';
  END IF;
END
$ensure_m2_agent$;
"""


def _verify() -> dict[str, Any]:
    """Read-only catalog check against production. Opens a normal connection with
    the app credential; touches nothing."""
    out: dict[str, Any] = {
        "vector_extension": False, "role_exists": False, "role_is_safe": None,
        "schema_exists": False,
    }
    try:
        import psycopg2  # noqa: PLC0415
    except Exception:
        out["error"] = "psycopg2 unavailable"
        return out
    env: dict[str, str] = {}
    dotenv = ROOT / ".env"
    if dotenv.exists():
        for line in dotenv.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    try:
        conn = psycopg2.connect(
            host=os.environ.get("DB_HOST") or env.get("DB_HOST", "localhost"),
            dbname=os.environ.get("DB_NAME") or env.get("DB_NAME", PRODUCTION_DB),
            user=os.environ.get("DB_USER") or env.get("DB_USER", "trade_ai"),
            password=os.environ.get("DB_PASSWORD") or env.get("DB_PASSWORD", ""),
            connect_timeout=5,
        )
    except Exception as e:
        # A fresh worktree has no .env by default (new-worktree.sh SOP Stage 5),
        # so say what to supply rather than just naming the exception class.
        out["error"] = (
            f"connect failed: {type(e).__name__} — set DB_HOST/DB_NAME/DB_USER/"
            "DB_PASSWORD in the environment, or run from a tree that has .env"
        )
        return out
    try:
        conn.set_session(readonly=True, autocommit=True)
        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM pg_extension WHERE extname='vector'")
            out["vector_extension"] = cur.fetchone() is not None
            cur.execute(
                "SELECT rolsuper, rolbypassrls, rolcreatedb, rolcreaterole "
                "FROM pg_roles WHERE rolname=%s", (ROLE,),
            )
            row = cur.fetchone()
            if row:
                out["role_exists"] = True
                # The RLS proof depends on this role being none of these.
                out["role_is_safe"] = not any(row)
            cur.execute("SELECT 1 FROM pg_namespace WHERE nspname='memory_r10_m2'")
            out["schema_exists"] = cur.fetchone() is not None
    finally:
        conn.close()
    return out


def _shred(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        subprocess.run(["shred", "-u", str(path)], check=True,
                       capture_output=True, timeout=30)
        return True
    except Exception:
        try:  # shred unavailable — overwrite then unlink
            n = path.stat().st_size
            with path.open("r+b") as fh:
                fh.write(secrets.token_bytes(max(n, 1)))
                fh.flush()
                os.fsync(fh.fileno())
            path.unlink()
            return True
        except Exception:
            return False


def provision(*, dry_run: bool) -> dict[str, Any]:
    out: dict[str, Any] = {
        "ok": False, "action": None, "secret_upserted": False,
        "dsn_len": 0, "sql_path": str(SQL_PATH), "dry_run": dry_run,
    }
    parts = _db_params()
    out["target"] = f"{parts['host']}:{parts['port']}/{parts['dbname']}"
    if parts["dbname"] != PRODUCTION_DB:
        out["error"] = (
            f"refusing: this script provisions the PRODUCTION role and DB_NAME is "
            f"{parts['dbname']!r}, not {PRODUCTION_DB!r}"
        )
        return out

    if dry_run:
        out["action"] = "would_generate_upsert_and_emit_sql"
        out["ok"] = True
        return out

    password = _gen_password()
    dsn = _build_dsn(parts, password)
    out["dsn_len"] = len(dsn)

    try:
        import secrets_admin  # noqa: PLC0415
        res = secrets_admin.set_secret(SECRET_NAME, dsn, actor="ensure_m2_agent_dsn")
        out["secret_upserted"] = bool(res.get("ok"))
    except Exception as e:
        out["error"] = f"set_secret failed: {type(e).__name__}"
        return out
    finally:
        dsn = ""

    if not out["secret_upserted"]:
        out["error"] = "set_secret returned not-ok; no SQL emitted"
        return out

    try:
        RUNTIME_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)
        # 0600 before any content is written — never briefly world-readable.
        fd = os.open(str(SQL_PATH), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(_sql_text(password))
    except Exception as e:
        out["error"] = f"sql emit failed: {type(e).__name__}"
        return out
    finally:
        password = ""

    out["action"] = "secret_upserted_and_sql_emitted"
    out["ok"] = True
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true",
                      help="report what would happen; generate nothing, write nothing")
    mode.add_argument("--verify", action="store_true",
                      help="read-only: has the operator applied the SQL yet?")
    ap.add_argument("--shred", action="store_true",
                    help="with --verify: securely delete the emitted SQL once the role exists")
    args = ap.parse_args(argv)

    if args.verify:
        out: dict[str, Any] = {"action": "verify", **_verify()}
        out["sql_present"] = SQL_PATH.exists()
        ready = bool(out.get("role_exists") and out.get("vector_extension"))
        if args.shred:
            if ready:
                out["sql_shredded"] = _shred(SQL_PATH)
            else:
                out["sql_shredded"] = False
                out["note"] = "not shredded: role/extension missing, SQL not applied yet"
        if out.get("role_exists") and out.get("role_is_safe") is False:
            out["ok"] = False
            out["error"] = (
                f"{ROLE} has SUPERUSER/BYPASSRLS/CREATEDB/CREATEROLE — the RLS "
                "isolation proof is void until those are removed"
            )
        else:
            out["ok"] = ready
        print(json.dumps(out, indent=2, sort_keys=True))
        return 0 if out["ok"] else 2

    out = provision(dry_run=args.dry_run)
    print(json.dumps(out, indent=2, sort_keys=True))
    if out["ok"] and not args.dry_run:
        print(
            "\nNext (the password is in Bitwarden SM and in the file below; it was "
            "never printed):\n"
            f"  sudo -u postgres psql -d {PRODUCTION_DB} -f {SQL_PATH}\n"
            "  scripts/secrets/ensure_m2_agent_dsn.py --verify --shred",
            file=sys.stderr,
        )
    return 0 if out["ok"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
